// Generated by scripts/migrate-content.mjs from shared/data.js — safe to hand-edit afterwards.
export type Localized = { pt: string; en: string };

export type Project = {
  id: string;
  name: string;
  year: string;
  category: Localized;
  role: Localized;
  stack: string[];
  summary: Localized;
  impact: Localized;
  url: string;
  accent: string;
  featured: boolean;
};

export const projects: Project[] = [
  {
    "id": "laravel-fintech",
    "name": "Laravel Fintech Core",
    "year": "2025",
    "category": {
      "pt": "Plataforma Fintech",
      "en": "Fintech Platform"
    },
    "role": {
      "pt": "Engenheiro Líder",
      "en": "Lead Engineer"
    },
    "stack": [
      "Laravel",
      "PostgreSQL",
      "Redis",
      "Docker"
    ],
    "summary": {
      "pt": "Core bancário com ledger de partidas dobradas, transações ACID e isolamento multi-tenant por schema. Auditoria e reconciliação de saldo rodam em O(log n) via índice composto em (account_id, created_at).",
      "en": "Banking core with double-entry ledger, ACID transactions and multi-tenant schema isolation. Balance audit and reconciliation run in O(log n) via a composite index on (account_id, created_at)."
    },
    "impact": {
      "pt": "Ledger append-only com constraint de unicidade em transaction_id, garantindo idempotência mesmo sob retry. Saldo é O(1) por leitura de cache e recalculável em O(n) a partir do histórico quando precisa auditar.",
      "en": "Append-only ledger with a uniqueness constraint on transaction_id, guaranteeing idempotency even under retries. Balance reads are O(1) via cache and recomputable in O(n) from history when an audit is needed."
    },
    "url": "https://github.com/vitorgabrieldev/laravel-fintech-core",
    "accent": "#c96442",
    "featured": true
  },
  {
    "id": "risklog",
    "name": "Risklog",
    "year": "2025",
    "category": {
      "pt": "Inteligência de Deploy",
      "en": "Deployment Intelligence"
    },
    "role": {
      "pt": "Full Stack",
      "en": "Full Stack"
    },
    "stack": [
      "Laravel",
      "CI/CD",
      "GitHub Actions"
    ],
    "summary": {
      "pt": "Integração CI/CD que classifica o risco de cada deploy: parseia o diff do PR, mapeia ownership via CODEOWNERS e estima blast radius em tempo linear O(n) sobre os arquivos alterados.",
      "en": "CI/CD integration that scores deploy risk: parses the PR diff, maps ownership via CODEOWNERS and estimates blast radius in linear time O(n) over the changed files."
    },
    "impact": {
      "pt": "Resultado da análise fica em cache por commit SHA, então PRs grandes não são reprocessados a cada push. O time adotou como checklist de release — menos surpresas após deploys.",
      "en": "Analysis results are cached by commit SHA, so large PRs aren't reprocessed on every push. The team adopted it as a release checklist — fewer surprises after deploys."
    },
    "url": "https://github.com/vitorgabrieldev/risklog-api",
    "accent": "#6b7a4a",
    "featured": true
  },
  {
    "id": "dubflow",
    "name": "DubFlow",
    "year": "2024",
    "category": {
      "pt": "Plataforma Social",
      "en": "Social Platform"
    },
    "role": {
      "pt": "Full Stack",
      "en": "Full Stack"
    },
    "stack": [
      "Laravel",
      "Next.js",
      "TypeScript"
    ],
    "summary": {
      "pt": "Plataforma comunitária para dubladores — casting, portfólio e mensagens diretas via WebSocket. Busca de perfis por voz/idioma usa índice invertido, filtro em O(log n) em vez de scan linear na tabela.",
      "en": "Community platform for voice-over professionals — casting, portfolio and direct messages over WebSocket. Profile search by voice/language uses an inverted index, filtering in O(log n) instead of a linear table scan."
    },
    "impact": {
      "pt": "Entregue de ponta a ponta: API Laravel, auth com JWT, frontend em Next.js, deploy em VPS. Arquitetura simples o bastante pra eu sozinho manter em produção sem susto.",
      "en": "Shipped end-to-end: Laravel API, JWT auth, Next.js frontend, VPS deploy. Architecture simple enough for me to maintain solo in production without surprises."
    },
    "url": "https://github.com/vitorgabrieldev/dubflow.pro.br",
    "accent": "#8a5a8c",
    "featured": true
  },
  {
    "id": "trabalho-amigo",
    "name": "Trabalho Amigo",
    "year": "2025",
    "category": {
      "pt": "Marketplace SaaS",
      "en": "SaaS Marketplace"
    },
    "role": {
      "pt": "Full Stack",
      "en": "Full Stack"
    },
    "stack": [
      "Laravel",
      "Next.js",
      "PostgreSQL",
      "Stripe",
      "Docker"
    ],
    "summary": {
      "pt": "Marketplace multitenant que conecta clientes a profissionais locais — limpeza, design, tecnologia. Busca combina full-text search com fuzzy matching por distância de Levenshtein pra tolerar erro de digitação.",
      "en": "Multitenant marketplace connecting clients to local professionals — cleaning, design, tech. Search combines full-text search with Levenshtein-distance fuzzy matching to tolerate typos."
    },
    "impact": {
      "pt": "Pagamentos via Stripe, 2FA, chat em tempo real por WebSocket e busca FTS + fuzzy no PostgreSQL. Mantive o schema simples — sem over-engineering num domínio que ainda estava validando product-market fit.",
      "en": "Stripe payments, 2FA, real-time WebSocket chat and FTS + fuzzy search on PostgreSQL. Kept the schema simple — no over-engineering on a domain still validating product-market fit."
    },
    "url": "https://github.com/vitorgabrieldev/trabalhoamigo.com.br",
    "accent": "#2d8a6e",
    "featured": true
  },
  {
    "id": "pett-love",
    "name": "Pett Love",
    "year": "2024",
    "category": {
      "pt": "Frontend · SPA",
      "en": "Frontend · SPA"
    },
    "role": {
      "pt": "Frontend",
      "en": "Frontend"
    },
    "stack": [
      "React",
      "TypeScript",
      "Tailwind",
      "Vite"
    ],
    "summary": {
      "pt": "Interface moderna e responsiva para plataforma de pet care — com rotas dinâmicas, animações fluidas e design system robusto.",
      "en": "Modern responsive interface for pet care platform — with dynamic routing, smooth animations and solid design system."
    },
    "impact": {
      "pt": "Implementei layout completo, interações e foi deployada em Vercel com builds otimizados.",
      "en": "Shipped complete layout, interactions and deployed on Vercel with optimized builds."
    },
    "url": "https://github.com/vitorgabrieldev/Pett-Love",
    "accent": "#e67e22",
    "featured": false
  },
  {
    "id": "terminal-simulator",
    "name": "Terminal Simulator",
    "year": "2024",
    "category": {
      "pt": "Ferramenta · Experimental",
      "en": "Tool · Experimental"
    },
    "role": {
      "pt": "Full Stack",
      "en": "Full Stack"
    },
    "stack": [
      "React",
      "Vite",
      "TypeScript"
    ],
    "summary": {
      "pt": "Simulador interativo de terminal com comandos reais — explore bash num navegador sem risco.",
      "en": "Interactive terminal simulator with real commands — explore bash in a browser safely."
    },
    "impact": {
      "pt": "Explorei React puro, renderização de conteúdo dinâmico e experiência de usuário style terminal.",
      "en": "Explored vanilla React, dynamic content rendering, and terminal-style UX."
    },
    "url": "https://github.com/vitorgabrieldev/terminal-simulator",
    "accent": "#16a34a",
    "featured": false
  },
  {
    "id": "immortal-scrollytelling",
    "name": "What would it be like to be immortal?",
    "year": "2024",
    "category": {
      "pt": "Storytelling · Interativo",
      "en": "Storytelling · Interactive"
    },
    "role": {
      "pt": "Full Stack",
      "en": "Full Stack"
    },
    "stack": [
      "React",
      "Tailwind",
      "GSAP",
      "Lenis",
      "Vite"
    ],
    "summary": {
      "pt": "Scrollytelling imersivo sobre a jornada de um ser humano imortal — narrativa visual com animações sincronizadas ao scroll.",
      "en": "Immersive scrollytelling about an immortal human's journey — visual narrative with scroll-synced animations."
    },
    "impact": {
      "pt": "Criei uma experiência interativa única explorando GSAP, smooth scroll com Lenis, e efeitos de partículas com TsParticles.",
      "en": "Built unique interactive experience exploring GSAP animations, smooth scrolling, and particle effects."
    },
    "url": "https://github.com/vitorgabrieldev/What-would-it-be-like-to-be-immortal",
    "accent": "#8b5cf6",
    "featured": false
  },
  {
    "id": "runrun-integration",
    "name": "Runrun.it API Integration",
    "year": "2024",
    "category": {
      "pt": "Dashboard · Integração",
      "en": "Dashboard · Integration"
    },
    "role": {
      "pt": "Full Stack",
      "en": "Full Stack"
    },
    "stack": [
      "PHP",
      "jQuery",
      "HTML/CSS"
    ],
    "summary": {
      "pt": "Dashboard gerencial que consome API do Runrun.it com foco em métricas — projetos, tasks, conclusão e riscos em tempo real.",
      "en": "Management dashboard consuming Runrun.it API with focus on metrics — projects, tasks, completion rates and risks."
    },
    "impact": {
      "pt": "Implementei 13+ métricas úteis para gestores com segurança (apenas leitura) e paginação eficiente de grandes volumes de dados.",
      "en": "Built 13+ useful metrics for managers with read-only security and efficient pagination for large datasets."
    },
    "url": "https://github.com/vitorgabrieldev/runrun-api-integration",
    "accent": "#3b82f6",
    "featured": false
  },
  {
    "id": "dubflow-game",
    "name": "DubFlow Game",
    "year": "2024",
    "category": {
      "pt": "Game · Física 2D",
      "en": "Game · 2D Physics"
    },
    "role": {
      "pt": "Game Dev",
      "en": "Game Dev"
    },
    "stack": [
      "Matter.js",
      "Vanilla JS",
      "HTML5/CSS3"
    ],
    "summary": {
      "pt": "Jogo de slingshot com simulação física realista — use force e ângulo para acertar alvos através de fases progressivas.",
      "en": "Slingshot game with realistic physics simulation — use force and angle to hit targets through progressive levels."
    },
    "impact": {
      "pt": "Explorei Matter.js para simulação de corpos rígidos, colisões e constraints — criando mecânica intuitiva e desafiadora.",
      "en": "Explored Matter.js for rigid body simulation, collisions and constraints — creating intuitive challenging gameplay."
    },
    "url": "https://github.com/vitorgabrieldev/matter.js-example",
    "accent": "#ec4899",
    "featured": false
  },
  {
    "id": "general-agent",
    "name": "General Agent Terminal",
    "year": "2025",
    "category": {
      "pt": "IA · Linux",
      "en": "AI · Linux"
    },
    "role": {
      "pt": "Experimental",
      "en": "Experimental"
    },
    "stack": [
      "Python",
      "Mistral",
      "Linux"
    ],
    "summary": {
      "pt": "Agente terminal com Mistral que raciocina sobre ações de shell antes de executá-las.",
      "en": "Mistral-powered terminal agent that reasons about shell actions before executing them."
    },
    "impact": {
      "pt": "Protótipo de pesquisa pessoal — explorando workflows de sysadmin guiados por LLM.",
      "en": "Personal research prototype — exploring LLM-driven sysadmin workflows."
    },
    "url": "https://github.com/vitorgabrieldev/general-agent-terminal-linux",
    "accent": "#3d5a7a",
    "featured": false
  },
  {
    "id": "blockchain",
    "name": "Blockchain Prototypes",
    "year": "2024",
    "category": {
      "pt": "Blockchain",
      "en": "Blockchain"
    },
    "role": {
      "pt": "Pesquisador",
      "en": "Researcher"
    },
    "stack": [
      "Solidity",
      "Ethereum",
      "Node.js"
    ],
    "summary": {
      "pt": "Experimentos com DApps, lógica de chain customizada e consenso — validando integrações descentralizadas.",
      "en": "Experiments with DApps, custom chain logic and consensus — validating decentralised integrations."
    },
    "impact": {
      "pt": "Aprofundei conhecimento em EVM, assinaturas e trade-offs on-chain vs off-chain.",
      "en": "Gained depth on EVM, signatures and on-chain vs off-chain trade-offs."
    },
    "url": "https://github.com/vitorgabrieldev/Blockchain",
    "accent": "#b58844",
    "featured": false
  },
  {
    "id": "motion-recognition",
    "name": "Hand Motion Recognition",
    "year": "2024",
    "category": {
      "pt": "Visão Computacional",
      "en": "Computer Vision"
    },
    "role": {
      "pt": "Full Stack",
      "en": "Full Stack"
    },
    "stack": [
      "Python",
      "OpenCV"
    ],
    "summary": {
      "pt": "Interface de gestos manuais em tempo real para otimização de interação.",
      "en": "Real-time hand gesture interface for interaction optimisation."
    },
    "impact": {
      "pt": "Explorei pipelines de CV e processamento de vídeo de baixa latência em hardware comum.",
      "en": "Explored CV pipelines and low-latency video processing on commodity hardware."
    },
    "url": "https://github.com/vitorgabrieldev/motion-recognition-for-interaction-optimization",
    "accent": "#4a7a6b",
    "featured": false
  },
  {
    "id": "rotina",
    "name": "Rotina",
    "year": "2024",
    "category": {
      "pt": "Ferramentas Internas",
      "en": "Internal Tools"
    },
    "role": {
      "pt": "Full Stack",
      "en": "Full Stack"
    },
    "stack": [
      "Laravel",
      "PHP"
    ],
    "summary": {
      "pt": "Plataforma de organização empresarial — cadência semanal, ownership, bloqueios.",
      "en": "Business organisation platform — weekly cadence, ownership, blockers."
    },
    "impact": {
      "pt": "Substituiu 3 planilhas para um time pequeno.",
      "en": "Replaced 3 spreadsheets for a small team."
    },
    "url": "https://github.com/vitorgabrieldev/rotina.pro.br",
    "accent": "#7a5a4a",
    "featured": false
  },
  {
    "id": "painel-startup",
    "name": "Risklog Admin Panel",
    "year": "2024",
    "category": {
      "pt": "Painel Administrativo",
      "en": "Admin Dashboard"
    },
    "role": {
      "pt": "Full Stack",
      "en": "Full Stack"
    },
    "stack": [
      "Laravel",
      "Blade",
      "Tailwind"
    ],
    "summary": {
      "pt": "Console de operações para o Risklog — deploys, usuários, limites de política.",
      "en": "Operations console for Risklog — deploys, users, policy thresholds."
    },
    "impact": {
      "pt": "Deu ao time de ops controle direto sem precisar de mão de obra de engenharia.",
      "en": "Gave the ops team direct control without engineering hand-offs."
    },
    "url": "https://github.com/vitorgabrieldev/painel.startup.dev.br",
    "accent": "#5a4a7a",
    "featured": false
  }
];
