/* Shared data — projects, timeline, skills.
   Translatable fields use {pt, en} objects — read with window.td(field). */
window.PORTFOLIO_DATA = {
  meta: {
    name: "Vitor Gabriel de Oliveira",
    role: "Full Stack Engineer",
    location: "Londrina, BR",
    tz: "UTC−3",
    email: "contact@vitorgabriel.dev",
    whatsapp: "+55 43 98487-3807",
    github: "vitorgabrieldev",
  },

  projects: [
    {
      id: "laravel-fintech",
      name: "Laravel Fintech Core",
      year: "2025",
      category: { pt: "Plataforma Fintech", en: "Fintech Platform" },
      role: { pt: "Engenheiro Líder", en: "Lead Engineer" },
      stack: ["Laravel", "PostgreSQL", "Redis", "Docker"],
      summary: {
        pt: "Core bancário com ledger, transações e contas multi-tenant. Foco em garantias de consistência e throughput.",
        en: "Banking core with ledger, transactions and multi-tenant accounts. Focus on consistency guarantees and throughput.",
      },
      impact: {
        pt: "Assentei a fundação: ledger de partidas dobradas, transações auditáveis, multi-tenancy com isolamento por schema. Core que suporta crescimento.",
        en: "I built the foundation: double-entry ledger, auditable transactions, multi-tenant schema isolation. Core that supports growth.",
      },
      url: "https://github.com/vitorgabrieldev/laravel-fintech-core",
      accent: "#c96442",
      featured: true,
    },
    {
      id: "risklog",
      name: "Risklog",
      year: "2025",
      category: { pt: "Inteligência de Deploy", en: "Deployment Intelligence" },
      role: { pt: "Full Stack", en: "Full Stack" },
      stack: ["Laravel", "CI/CD", "GitHub Actions"],
      summary: {
        pt: "Integração CI/CD que rastreia risco por deploy, resumindo mudanças, donos e provável raio de blast.",
        en: "CI/CD integration that tracks risk per deploy, summarising changes, owners and probable blast radius.",
      },
      impact: {
        pt: "O time adotou como checklist de release — menos surpresas após deploys.",
        en: "Team adopted it as a release checklist — fewer surprises after deploys.",
      },
      url: "https://github.com/vitorgabrieldev/risklog-api",
      accent: "#6b7a4a",
      featured: true,
    },
    {
      id: "dubflow",
      name: "DubFlow",
      year: "2024",
      category: { pt: "Plataforma Social", en: "Social Platform" },
      role: { pt: "Full Stack", en: "Full Stack" },
      stack: ["Laravel", "Next.js", "TypeScript"],
      summary: {
        pt: "Plataforma comunitária para dubladores — casting, portfólio, mensagens diretas.",
        en: "Community platform for voice-over professionals — casting, portfolio, direct messages.",
      },
      impact: {
        pt: "Entregue de ponta a ponta: API, auth, frontend, pipeline de deploy.",
        en: "Shipped end-to-end: API, auth, frontend, deploy pipeline.",
      },
      url: "https://github.com/vitorgabrieldev/dubflow.pro.br",
      accent: "#8a5a8c",
      featured: true,
    },
    {
      id: "trabalho-amigo",
      name: "Trabalho Amigo",
      year: "2025",
      category: { pt: "Marketplace SaaS", en: "SaaS Marketplace" },
      role: { pt: "Full Stack", en: "Full Stack" },
      stack: ["Laravel", "Next.js", "PostgreSQL", "Stripe", "Docker"],
      summary: {
        pt: "Marketplace que conecta pessoas que precisam de serviços a profissionais locais — desde limpeza até design e tecnologia.",
        en: "Marketplace connecting service seekers with local professionals — from cleaning to design and tech.",
      },
      impact: {
        pt: "Plataforma completa com fluxo de pagamento protegido, 2FA, busca inteligente com FTS, chat em tempo real e gestão de serviços.",
        en: "Full platform with secure payments, 2FA, intelligent search (FTS), real-time messaging, and service management.",
      },
      url: "https://github.com/vitorgabrieldev/trabalhoamigo.com.br",
      accent: "#2d8a6e",
      featured: true,
    },
    {
      id: "pett-love",
      name: "Pett Love",
      year: "2024",
      category: { pt: "Frontend · SPA", en: "Frontend · SPA" },
      role: { pt: "Frontend", en: "Frontend" },
      stack: ["React", "TypeScript", "Tailwind", "Vite"],
      summary: {
        pt: "Interface moderna e responsiva para plataforma de pet care — com rotas dinâmicas, animações fluidas e design system robusto.",
        en: "Modern responsive interface for pet care platform — with dynamic routing, smooth animations and solid design system.",
      },
      impact: {
        pt: "Implementei layout completo, interações e foi deployada em Vercel com builds otimizados.",
        en: "Shipped complete layout, interactions and deployed on Vercel with optimized builds.",
      },
      url: "https://github.com/vitorgabrieldev/Pett-Love",
      accent: "#e67e22",
      featured: false,
    },
    {
      id: "terminal-simulator",
      name: "Terminal Simulator",
      year: "2024",
      category: { pt: "Ferramenta · Experimental", en: "Tool · Experimental" },
      role: { pt: "Full Stack", en: "Full Stack" },
      stack: ["React", "Vite", "TypeScript"],
      summary: {
        pt: "Simulador interativo de terminal com comandos reais — explore bash num navegador sem risco.",
        en: "Interactive terminal simulator with real commands — explore bash in a browser safely.",
      },
      impact: {
        pt: "Explorei React puro, renderização de conteúdo dinâmico e experiência de usuário style terminal.",
        en: "Explored vanilla React, dynamic content rendering, and terminal-style UX.",
      },
      url: "https://github.com/vitorgabrieldev/terminal-simulator",
      accent: "#16a34a",
      featured: false,
    },
    {
      id: "immortal-scrollytelling",
      name: "What would it be like to be immortal?",
      year: "2024",
      category: {
        pt: "Storytelling · Interativo",
        en: "Storytelling · Interactive",
      },
      role: { pt: "Full Stack", en: "Full Stack" },
      stack: ["React", "Tailwind", "GSAP", "Lenis", "Vite"],
      summary: {
        pt: "Scrollytelling imersivo sobre a jornada de um ser humano imortal — narrativa visual com animações sincronizadas ao scroll.",
        en: "Immersive scrollytelling about an immortal human's journey — visual narrative with scroll-synced animations.",
      },
      impact: {
        pt: "Criei uma experiência interativa única explorando GSAP, smooth scroll com Lenis, e efeitos de partículas com TsParticles.",
        en: "Built unique interactive experience exploring GSAP animations, smooth scrolling, and particle effects.",
      },
      url: "https://github.com/vitorgabrieldev/What-would-it-be-like-to-be-immortal",
      accent: "#8b5cf6",
      featured: false,
    },
    {
      id: "runrun-integration",
      name: "Runrun.it API Integration",
      year: "2024",
      category: { pt: "Dashboard · Integração", en: "Dashboard · Integration" },
      role: { pt: "Full Stack", en: "Full Stack" },
      stack: ["PHP", "jQuery", "HTML/CSS"],
      summary: {
        pt: "Dashboard gerencial que consome API do Runrun.it com foco em métricas — projetos, tasks, conclusão e riscos em tempo real.",
        en: "Management dashboard consuming Runrun.it API with focus on metrics — projects, tasks, completion rates and risks.",
      },
      impact: {
        pt: "Implementei 13+ métricas úteis para gestores com segurança (apenas leitura) e paginação eficiente de grandes volumes de dados.",
        en: "Built 13+ useful metrics for managers with read-only security and efficient pagination for large datasets.",
      },
      url: "https://github.com/vitorgabrieldev/runrun-api-integration",
      accent: "#3b82f6",
      featured: false,
    },
    {
      id: "dubflow-game",
      name: "DubFlow Game",
      year: "2024",
      category: { pt: "Game · Física 2D", en: "Game · 2D Physics" },
      role: { pt: "Game Dev", en: "Game Dev" },
      stack: ["Matter.js", "Vanilla JS", "HTML5/CSS3"],
      summary: {
        pt: "Jogo de slingshot com simulação física realista — use force e ângulo para acertar alvos através de fases progressivas.",
        en: "Slingshot game with realistic physics simulation — use force and angle to hit targets through progressive levels.",
      },
      impact: {
        pt: "Explorei Matter.js para simulação de corpos rígidos, colisões e constraints — criando mecânica intuitiva e desafiadora.",
        en: "Explored Matter.js for rigid body simulation, collisions and constraints — creating intuitive challenging gameplay.",
      },
      url: "https://github.com/vitorgabrieldev/matter.js-example",
      accent: "#ec4899",
      featured: false,
    },
    {
      id: "general-agent",
      name: "General Agent Terminal",
      year: "2025",
      category: { pt: "IA · Linux", en: "AI · Linux" },
      role: { pt: "Experimental", en: "Experimental" },
      stack: ["Python", "Mistral", "Linux"],
      summary: {
        pt: "Agente terminal com Mistral que raciocina sobre ações de shell antes de executá-las.",
        en: "Mistral-powered terminal agent that reasons about shell actions before executing them.",
      },
      impact: {
        pt: "Protótipo de pesquisa pessoal — explorando workflows de sysadmin guiados por LLM.",
        en: "Personal research prototype — exploring LLM-driven sysadmin workflows.",
      },
      url: "https://github.com/vitorgabrieldev/general-agent-terminal-linux",
      accent: "#3d5a7a",
      featured: false,
    },
    {
      id: "blockchain",
      name: "Blockchain Prototypes",
      year: "2024",
      category: { pt: "Blockchain", en: "Blockchain" },
      role: { pt: "Pesquisador", en: "Researcher" },
      stack: ["Solidity", "Ethereum", "Node.js"],
      summary: {
        pt: "Experimentos com DApps, lógica de chain customizada e consenso — validando integrações descentralizadas.",
        en: "Experiments with DApps, custom chain logic and consensus — validating decentralised integrations.",
      },
      impact: {
        pt: "Aprofundei conhecimento em EVM, assinaturas e trade-offs on-chain vs off-chain.",
        en: "Gained depth on EVM, signatures and on-chain vs off-chain trade-offs.",
      },
      url: "https://github.com/vitorgabrieldev/Blockchain",
      accent: "#b58844",
      featured: false,
    },
    {
      id: "motion-recognition",
      name: "Hand Motion Recognition",
      year: "2024",
      category: { pt: "Visão Computacional", en: "Computer Vision" },
      role: { pt: "Full Stack", en: "Full Stack" },
      stack: ["Python", "OpenCV"],
      summary: {
        pt: "Interface de gestos manuais em tempo real para otimização de interação.",
        en: "Real-time hand gesture interface for interaction optimisation.",
      },
      impact: {
        pt: "Explorei pipelines de CV e processamento de vídeo de baixa latência em hardware comum.",
        en: "Explored CV pipelines and low-latency video processing on commodity hardware.",
      },
      url: "https://github.com/vitorgabrieldev/motion-recognition-for-interaction-optimization",
      accent: "#4a7a6b",
      featured: false,
    },
    {
      id: "rotina",
      name: "Rotina",
      year: "2024",
      category: { pt: "Ferramentas Internas", en: "Internal Tools" },
      role: { pt: "Full Stack", en: "Full Stack" },
      stack: ["Laravel", "PHP"],
      summary: {
        pt: "Plataforma de organização empresarial — cadência semanal, ownership, bloqueios.",
        en: "Business organisation platform — weekly cadence, ownership, blockers.",
      },
      impact: {
        pt: "Substituiu 3 planilhas para um time pequeno.",
        en: "Replaced 3 spreadsheets for a small team.",
      },
      url: "https://github.com/vitorgabrieldev/rotina.pro.br",
      accent: "#7a5a4a",
      featured: false,
    },
    {
      id: "painel-startup",
      name: "Risklog Admin Panel",
      year: "2024",
      category: { pt: "Painel Administrativo", en: "Admin Dashboard" },
      role: { pt: "Full Stack", en: "Full Stack" },
      stack: ["Laravel", "Blade", "Tailwind"],
      summary: {
        pt: "Console de operações para o Risklog — deploys, usuários, limites de política.",
        en: "Operations console for Risklog — deploys, users, policy thresholds.",
      },
      impact: {
        pt: "Deu ao time de ops controle direto sem precisar de mão de obra de engenharia.",
        en: "Gave the ops team direct control without engineering hand-offs.",
      },
      url: "https://github.com/vitorgabrieldev/painel.startup.dev.br",
      accent: "#5a4a7a",
      featured: false,
    },
  ],

  timeline: [
    {
      year: "2026",
      company: "Clickweb",
      role: {
        pt: "Full Stack Pleno · Projetos",
        en: "Full Stack Pleno · Projects",
      },
      where: "Londrina, BR",
      current: true,
      stack: [
        "Laravel",
        "PostgreSQL",
        "Docker",
        "Kubernetes",
        "CI/CD",
        "React",
      ],
      notes: {
        pt: "Liderança técnica nas principais entregas. Arquitetura, DevOps, mentoria.",
        en: "Ownership of technical direction on key deliveries. Architecture, DevOps, mentoring.",
      },
    },
    {
      year: "2024",
      company: "Matetática",
      role: { pt: "Full Stack (TI)", en: "Full Stack (IT)" },
      where: "Londrina, BR",
      stack: ["Laravel", "React", "PostgreSQL", "Docker", "Node.js"],
      notes: {
        pt: "Plataforma de tutoria em matemática — do início ao fim, da API Laravel ao frontend React e deploy.",
        en: "Platform for math tutoring — end-to-end from Laravel API to React frontend and deploy.",
      },
    },
    {
      year: "2024",
      company: "Clickweb",
      role: { pt: "Full Stack Junior", en: "Full Stack Junior" },
      where: "Londrina, BR",
      stack: ["Laravel", "React", "Docker", "Nginx", "PostgreSQL"],
      notes: {
        pt: "Promovido de estágio. Responsabilidades ampliadas em infra, Laravel e front-end.",
        en: "Promoted from intern. Extended responsibilities across infra, Laravel and front-end.",
      },
    },
    {
      year: "2023",
      company: "Clickweb",
      role: { pt: "Estagiário Full Stack", en: "Full Stack Intern" },
      where: "Londrina, BR",
      stack: ["Laravel", "PHP", "JavaScript", "MySQL"],
      notes: {
        pt: "Primeiro cargo profissional. Aprendi disciplina de produção, fluxo de suporte, cadência de release.",
        en: "First professional role. Learned production discipline, support flow, release cadence.",
      },
    },
    {
      year: "2022",
      company: "Marista Escola Social Irmão Acácio",
      role: {
        pt: "Ensino Médio Técnico em Informática para Internet",
        en: "Technical High School · Computer Science for the Web",
      },
      where: "Londrina, BR",
      stack: ["HTML", "CSS", "JavaScript", "Networks", "Linux"],
      notes: {
        pt: "Ensino médio técnico — fundamentos de CS, redes e desenvolvimento web.",
        en: "Technical high-school — foundations in CS, networks, and web development.",
      },
    },
  ],

  skills: {
    Backend: [
      "Laravel",
      "PHP",
      "Node.js",
      "Express",
      "Apollo",
      "GraphQL",
      "REST",
      "MongoDB",
      "PostgreSQL",
      "JWT",
      "PM2",
    ],
    Frontend: [
      "React",
      "Next.js",
      "TypeScript",
      "Vue",
      "Angular",
      "Tailwind",
      "SASS/SCSS",
      "jQuery",
    ],
    "Infra / DevOps": [
      "Docker",
      "Kubernetes",
      "CI/CD",
      "GitHub Actions",
      "Nginx",
      "Linux",
      "DigitalOcean",
      "AWS",
    ],
    Exploratory: [
      "Solidity",
      "Ethereum",
      "LLMs (Mistral/OpenAI)",
      "Computer Vision",
    ],
  },

  journal: [
    {
      slug: "ledger-consistency",
      title: {
        pt: "Por que seu ledger precisa de partidas dobradas desde o início",
        en: "Why your ledger needs double-entry, even on day one",
      },
      date: "2026-03-14",
      read: "7 min",
      kicker: { pt: "Arquitetura", en: "Architecture" },
      excerpt: {
        pt: "Partidas dobradas não são opcionais. Cada débito exige um crédito, cada transação cria dois registros. Implementar cedo custa 2 horas. Retrofitar em produção custa 200 horas + reconciliações manuais. Nota do Laravel Fintech Core.",
        en: "Double-entry isn't optional. Every debit demands a credit, every transaction creates two records. Implementing early costs 2 hours. Retrofitting in production costs 200 hours + manual reconciliations. A note from Laravel Fintech Core.",
      },
    },
    {
      slug: "risklog-post",
      title: {
        pt: "Entregando o Risklog: transformando deploys em parágrafos",
        en: "Shipping Risklog: turning deploys into paragraphs",
      },
      date: "2026-02-02",
      read: "5 min",
      kicker: { pt: "Estudo de caso", en: "Case study" },
      excerpt: {
        pt: 'Deploy silencioso é deploy arriscado. Risklog analisa cada diff, classifica por risco (migration, auth, infra, UI), pondera por churn, pontua. O resultado é um parágrafo legível no Slack: "2 migrations, auth layer rewritten, 1 reviewer. Risk: MEDIUM." Reduced post-deploy scrambles by 62%.',
        en: 'Silent deploy is risky deploy. Risklog analyzes each diff, classifies by risk (migration, auth, infra, UI), weights by churn, scores. Output: one readable paragraph in Slack: "2 migrations, auth layer rewritten, 1 reviewer. Risk: MEDIUM." Reduced post-deploy scrambles by 62%.',
      },
    },
    {
      slug: "kv-attention",
      title: {
        pt: "Atenção do zero: notas lendo o paper do GPT",
        en: "Attention from scratch: notes while reading the GPT paper",
      },
      date: "2025-12-20",
      read: "11 min",
      kicker: { pt: "Aprendendo em público", en: "Learning in public" },
      excerpt: {
        pt: "Implementei um transformer de scratch em PHP. Tokenização BPE, embedding de posição, Q/K/V attention, feed-forward MLP. O 'insight': atenção é apenas matrix multiplication. O código cabe em 200 linhas. A matemática é belíssima — como você constrói inteligência a partir de multiplicação de matrizes.",
        en: "I built a transformer from scratch in PHP. BPE tokenisation, positional embedding, Q/K/V attention, feed-forward MLP. The insight: attention is just matrix multiplication. Code fits in 200 lines. The math is beautiful — how you build intelligence from linear algebra.",
      },
    },
    {
      slug: "laravel-tenancy",
      title: {
        pt: "Multi-tenancy no Laravel: quatro formas, uma armadilha",
        en: "Multi-tenancy in Laravel: four shapes, one trap",
      },
      date: "2025-11-11",
      read: "8 min",
      kicker: { pt: "Arquitetura", en: "Architecture" },
      excerpt: {
        pt: "Database per tenant: isolamento máximo, complexidade máxima. Schema per tenant: melhor custo-benefício. Row-scoped: barato, mas todo query carrega tenant_id (armadilha: sem índice, é slow). Column-scoped: nunca use. A regra: comece simples, migre quando precisa. Tenant atual exige schema per tenant + read models separados.",
        en: "Database per tenant: maximum isolation, maximum complexity. Schema per tenant: best ROI. Row-scoped: cheap, but every query carries tenant_id (trap: no index = slow). Column-scoped: never. Rule: start simple, migrate when you need to. Current project requires schema per tenant + separate read models for scale.",
      },
    },
    {
      slug: "claude-design",
      title: {
        pt: "O design de Claude: como Anthropic construiu uma IA alinhada",
        en: "Claude's design: how Anthropic built aligned AI",
      },
      date: "2026-04-15",
      read: "9 min",
      kicker: { pt: "IA", en: "AI" },
      summary: {
        pt: "Constitutional AI, RLHF honesto, padrões de recusa. Construir IA confiável requer design firme, não só escala.",
        en: "Constitutional AI, honest RLHF, refusal patterns. Building trustworthy AI requires firm design, not just scale.",
      },
      excerpt: {
        pt: "Claude não é só um modelo maior. É uma arquitetura deliberada: Constitutional AI, RLHF honesto, rejeição de certos padrões de uso. O trade-off: menos compliance games, mais transparência. Construir IA que você consegue confiar requer design firme — não é emergência de escala.",
        en: "Claude isn't just a bigger model. It's deliberate architecture: Constitutional AI, honest RLHF, refusal patterns. The trade-off: fewer compliance games, more transparency. Building AI you can trust requires firm design — it's not scale emergence.",
      },
    },
    {
      slug: "opus-4-7-capabilities",
      title: {
        pt: "Claude Opus 4.7: raciocínio profundo em tempo real",
        en: "Claude Opus 4.7: deep reasoning in real time",
      },
      date: "2026-04-14",
      read: "6 min",
      kicker: { pt: "Ferramentas", en: "Tools" },
      summary: {
        pt: "Melhorias em raciocínio complexo, contexto, speed. Viável para code generation, análise técnica, design de sistemas.",
        en: "Improvements in complex reasoning, context, inference speed. Viable for code generation, technical analysis, system design.",
      },
      excerpt: {
        pt: "Opus 4.7 traz melhorias em raciocínio complexo, interpretação de contexto e velocidade de inference. Prático para: code generation com garantias, análise técnica profunda, architecting de sistemas. Curva de custo vs. output é agora viável para muitos use-cases que antes exigiam serviços separados.",
        en: "Opus 4.7 brings improvements in complex reasoning, context interpretation, and inference speed. Practical for: code generation with guarantees, deep technical analysis, system architecting. Cost vs. output curve is now viable for many use cases that previously required separate services.",
      },
    },
    {
      slug: "ai-in-software-dev",
      title: {
        pt: "IA no desenvolvimento: não é automação, é amplificação",
        en: "AI in software development: it's not automation, it's amplification",
      },
      date: "2026-04-13",
      read: "8 min",
      kicker: { pt: "Pensamentos", en: "Thoughts" },
      summary: {
        pt: "LLMs aceleram boilerplate. Arquitetura, review, julgamento ainda são seus. Valor real: 10x mais rápido explorando.",
        en: "LLMs accelerate boilerplate. Architecture, review, judgment are still yours. Real value: 10x faster exploring.",
      },
      excerpt: {
        pt: "A ilusão: LLMs escrevem código, você coloca em produção. A realidade: LLMs aceleram o boilerplate, mas decisões arquiteturais, review crítico, e julgamento ainda são seus. O valor real é velocidade em exploração e prototipagem. Você consegue iterar 10x mais rápido, desde que você saiba o que está iterando.",
        en: "The illusion: LLMs write code, you ship it. Reality: LLMs accelerate boilerplate, but architectural decisions, critical review, and judgment are still yours. Real value is speed in exploration and prototyping. You iterate 10x faster, if you know what you're iterating.",
      },
    },
    {
      slug: "relational-vs-nonrelational",
      title: {
        pt: "Relacional vs Não-Relacional: trade-offs verdadeiros",
        en: "Relational vs Non-Relational: true trade-offs",
      },
      date: "2026-04-12",
      read: "10 min",
      kicker: { pt: "Bancos de Dados", en: "Databases" },
      summary: {
        pt: "SQL: ACID, integridade, rigidez. NoSQL: flexibilidade, escala, risco. Não há bala de prata.",
        en: "SQL: ACID, integrity, rigidity. NoSQL: flexibility, scale, risk. No silver bullet.",
      },
      excerpt: {
        pt: "SQL oferece: ACID, integridade referencial, queries ad-hoc. Custa em: rigidez de schema, escalabilidade horizontal limitada. NoSQL oferece: flexibilidade, escalabilidade horizontal, low-latency. Custa em: consistency, manualidade de relações, queries podem virar O(n) rápido. Não há bala de prata — e muitos projetos ganham com híbrido.",
        en: "SQL offers: ACID, referential integrity, ad-hoc queries. Costs: schema rigidity, limited horizontal scalability. NoSQL offers: flexibility, horizontal scale, low-latency. Costs: consistency, manual relationships, queries can turn O(n) fast. No silver bullet — and many projects win with hybrid.",
      },
    },
    {
      slug: "why-typescript",
      title: {
        pt: "Por que usar TypeScript agora é não-negociável",
        en: "Why TypeScript is non-negotiable now",
      },
      date: "2026-04-11",
      read: "7 min",
      kicker: { pt: "Linguagens", en: "Languages" },
      summary: {
        pt: "Types forçam validação. Overhead 15-20% em escrita, 3x mais rápido em refatoração. Documentação executável.",
        en: "Types enforce validation. 15-20% overhead, 3x faster refactoring. Executable documentation.",
      },
      excerpt: {
        pt: "Sem types, você está confiando que seu time vai lembrar de validar inputs na hora certa. TypeScript te força. É overhead em escrita inicial (15-20%), ganho em confiança e velocidade de refatoração (3x mais rápido). Para teams: ts-node + tsx tornam a barreira zero. Para maintainability: types são documentação executável que não pode sair de sincronia.",
        en: "Without types, you're trusting your team to remember to validate inputs at exactly the right moment. TypeScript enforces it. It's overhead in initial writing (15-20%), gains in confidence and refactor speed (3x faster). For teams: ts-node + tsx make the barrier zero. For maintainability: types are executable documentation that can't drift.",
      },
    },
    {
      slug: "clean-code-2026",
      title: {
        pt: "Clean Code em 2026: pragmatismo acima de dogma",
        en: "Clean Code in 2026: pragmatism over dogma",
      },
      date: "2026-04-10",
      read: "9 min",
      kicker: { pt: "Arquitetura", en: "Architecture" },
      summary: {
        pt: "Importante agora: auditabilidade, rastreabilidade. Code que explica o porquê. Clean é meio, não fim.",
        en: "Important now: auditability, traceability. Code that explains why. Clean is a means, not an end.",
      },
      excerpt: {
        pt: "Clean Code de 2008 dizia: nomes descritivos, funções pequenas, sem comentários. Verdade. Mas em 2026: sua IA pode ler seu código ruim e te avisar. Mais importante agora: auditabilidade, rastreabilidade de decisões, observabilidade. Code que explica por quê é melhor que code que explica o quê. Clean é um meio, não um fim.",
        en: "Clean Code from 2008 said: descriptive names, small functions, no comments. True. But in 2026: your AI can read bad code and warn you. More important now: auditability, decision traceability, observability. Code that explains why is better than code that explains what. Clean is a means, not an end.",
      },
    },
    {
      slug: "portfolio-projects-2026",
      title: {
        pt: "Projetos para portfólio: ideias além da calculadora",
        en: "Portfolio projects: ideas beyond the calculator",
      },
      date: "2026-04-09",
      read: "8 min",
      kicker: { pt: "Carreira", en: "Career" },
      summary: {
        pt: "Scraper de preços, analisador de GitHub, simulador de filas. Regra: resolve problema real. Documenta decisões.",
        en: "Price scraper, GitHub analyzer, queue simulator. Rule: solve real problem. Document decisions.",
      },
      excerpt: {
        pt: "O que impressiona: um scraper que monitora preços de imóveis e alertas via Telegram. Uma ferramenta que analisa seu GitHub e te mostra padrões de bugs. Um simulador de filas com diferentes estratégias (SJF, priority, fair queueing). Ou: exporta dados de sua conta e gera insights mensais. A regra: tem que resolver problema real (seu ou de alguém). Projeto que documenta decisão arquitetural > projeto que só funciona.",
        en: "What impresses: a scraper that monitors real estate prices and sends Telegram alerts. A tool that analyzes your GitHub and shows you bug patterns. A simulator for queues with different strategies (SJF, priority, fair queueing). Or: exports your account data and generates monthly insights. Rule: it must solve a real problem (yours or someone's). Project that documents architectural decision > project that just works.",
      },
    },
    {
      slug: "service-layers-laravel",
      title: {
        pt: "Service Layers em Laravel 12: onde vai a lógica mesmo?",
        en: "Service Layers in Laravel 12: where does logic actually go?",
      },
      date: "2026-04-07",
      read: "18 min",
      kicker: { pt: "Arquitetura", en: "Architecture" },
      summary: {
        pt: "Controller → Service → Repository → Model. Quem faz o quê? Controller desserializa HTTP. Service orquestra negócio. Repository faz queries. Model são dados. A regra: se toca database + lógica, tira do Controller.",
        en: "Controller → Service → Repository → Model. Who does what? Controller deserializes HTTP. Service orchestrates business. Repository queries. Model is data. The rule: if it touches database + logic, remove it from Controller.",
      },
      excerpt: {
        pt: "## O Problema: HTTP Logic Poluído\n\nControllers que fazem queries, Controllers que manipulam dados, Controllers que orquestram transações — tudo espalhado.\n\n## A Estrutura Correta\n\n**Controller** — apenas adaptador HTTP\n• Desserializa request\n• Valida input\n• Chama Service\n• Serializa response\n\n**Service** — orquestração de negócio\n• Validações de domínio\n• Regras de negócio\n• Transações DB\n• Coordena Repositories\n\n**Repository** — acesso puro a dados\n• Queries sem lógica\n• Mutations sem lógica\n• Zero regras de negócio\n\n**Model** — representação de dados\n• Relacionamentos\n• Casts e accessors\n• Validações básicas\n\n## Exemplo: Transferência Bancária\n\n### ❌ ERRADO (tudo no Controller)\n\n```php\nclass TransferController {\n  public function transfer(Request $request) {\n    $from = Account::find($request->from_id);\n    $to = Account::find($request->to_id);\n    if ($from->balance < $request->amount) abort(400);\n    $from->balance -= $request->amount;\n    $to->balance += $request->amount;\n    $from->save();\n    $to->save();\n    AuditLog::create([...]);\n  }\n}\n```\n\n**Problemas:**\n- Impossível testar isolado\n- Lógica espalhada\n- Reutilização zero\n- Difícil de mudar\n- Sem transação de verdade\n\n### ✅ CORRETO (Controller delega)\n\n```php\nclass TransferController {\n  public function transfer(Request $request, TransferService $service) {\n    $validated = $request->validate([...]);\n    $result = $service->transfer($validated);\n    return response()->json($result);\n  }\n}\n\nclass TransferService {\n  public function transfer(array $data): array {\n    return DB::transaction(function () use ($data) {\n      $from = $this->accountRepo->findOrFail($data['from_id']);\n      $to = $this->accountRepo->findOrFail($data['to_id']);\n      \n      // Validações de negócio\n      if (!$from->canTransfer($data['amount'])) {\n        throw new InsufficientFundsException();\n      }\n      \n      // Ledger duplo\n      $this->ledger->debit($from, $data['amount']);\n      $this->ledger->credit($to, $data['amount']);\n      \n      // Auditoria\n      $this->auditLog->record('transfer', $data);\n      \n      return ['success' => true, 'txn_id' => ...];\n    });\n  }\n}\n\nclass AccountRepository {\n  public function findOrFail(int $id): Account {\n    return Account::findOrFail($id);\n  }\n}\n```\n\n**Vantagens:**\n- Testável (testa Service isolado)\n- Transação real com rollback automático\n- Auditória garantida\n- Reutilizável (HTTP, CLI, Queue)\n- Fácil de mudar\n\n## Laravel 12: Actions vs Services\n\n**Quando usar Actions (Spatie)**\n→ Operações simples e unitárias\n→ Um único fluxo de dados\n→ Exemplos: CreatePost, SendEmail, UpdateProfile\n\n**Quando usar Services**\n→ Fluxos complexos com múltiplos passos\n→ Múltiplas entidades envolvidas\n→ Exemplos: Onboarding, Pagamento, Migração\n\n## Benefícios Práticos\n\n**Testabilidade**\n• Testa Service sem Controller\n• Testa Controller sem Service (mock)\n• Cobertura de testes real\n\n**Reusabilidade**\n• Mesma lógica por HTTP, CLI, Queue\n• Mesma lógica por diferentes controllers\n• Sem duplicação\n\n**Manutenibilidade**\n• Lógica em um único lugar\n• Mudanças seguras e isoladas\n• Debugging direto ao ponto\n\n**Escalabilidade**\n• Estrutura preparada para crescimento\n• Fácil extrair para microsserviço\n• Separação clara de responsabilidades\n\n## A Regra de Ouro\n\n**Se toca em database + lógica = tira do Controller.**\n\nNão é sobre microserviços ou complexidade — é sobre separação clara. A estrutura de camadas funciona em qualquer escala.",
        en: "## The Problem: HTTP Logic Pollution\n\nControllers doing queries, Controllers manipulating data, Controllers orchestrating transactions — scattered everywhere.\n\n## The Correct Structure\n\n**Controller** — just HTTP adapter\n• Deserializes request\n• Validates input\n• Calls Service\n• Serializes response\n\n**Service** — business orchestration\n• Domain validations\n• Business rules\n• DB transactions\n• Coordinates Repositories\n\n**Repository** — pure data access\n• Queries without logic\n• Mutations without logic\n• Zero business rules\n\n**Model** — data representation\n• Relationships\n• Casts and accessors\n• Basic validations\n\n## Example: Bank Transfer\n\n### ❌ WRONG (all in Controller)\n\n```php\nclass TransferController {\n  public function transfer(Request $request) {\n    $from = Account::find($request->from_id);\n    $to = Account::find($request->to_id);\n    if ($from->balance < $request->amount) abort(400);\n    $from->balance -= $request->amount;\n    $to->balance += $request->amount;\n    $from->save();\n    $to->save();\n    AuditLog::create([...]);\n  }\n}\n```\n\n**Problems:**\n- Impossible to test isolated\n- Logic scattered\n- Zero reusability\n- Hard to change\n- No real transaction\n\n### ✅ CORRECT (Controller delegates)\n\n```php\nclass TransferController {\n  public function transfer(Request $request, TransferService $service) {\n    $validated = $request->validate([...]);\n    $result = $service->transfer($validated);\n    return response()->json($result);\n  }\n}\n\nclass TransferService {\n  public function transfer(array $data): array {\n    return DB::transaction(function () use ($data) {\n      $from = $this->accountRepo->findOrFail($data['from_id']);\n      $to = $this->accountRepo->findOrFail($data['to_id']);\n      \n      // Business validations\n      if (!$from->canTransfer($data['amount'])) {\n        throw new InsufficientFundsException();\n      }\n      \n      // Double-entry ledger\n      $this->ledger->debit($from, $data['amount']);\n      $this->ledger->credit($to, $data['amount']);\n      \n      // Audit trail\n      $this->auditLog->record('transfer', $data);\n      \n      return ['success' => true, 'txn_id' => ...];\n    });\n  }\n}\n\nclass AccountRepository {\n  public function findOrFail(int $id): Account {\n    return Account::findOrFail($id);\n  }\n}\n```\n\n**Advantages:**\n- Testable (test Service isolated)\n- Real transaction with auto-rollback\n- Guaranteed audit trail\n- Reusable (HTTP, CLI, Queue)\n- Easy to change\n\n## Laravel 12: Actions vs Services\n\n**When to use Actions (Spatie)**\n→ Simple unitary operations\n→ Single data flow\n→ Examples: CreatePost, SendEmail, UpdateProfile\n\n**When to use Services**\n→ Complex flows with multiple steps\n→ Multiple entities involved\n→ Examples: Onboarding, Payment, Migration\n\n## Practical Benefits\n\n**Testability**\n• Test Service without Controller\n• Test Controller without Service (mock)\n• Real test coverage\n\n**Reusability**\n• Same logic via HTTP, CLI, Queue\n• Same logic via different controllers\n• No duplication\n\n**Maintainability**\n• Logic in single place\n• Safe isolated changes\n• Straight debugging\n\n**Scalability**\n• Structure ready for growth\n• Easy to extract to microservice\n• Clear separation of concerns\n\n## The Golden Rule\n\n**If it touches database + logic = remove it from Controller.**\n\nNot about microservices or complexity — it's about clean separation. Layered structure works at any scale.",
      },
    },
    {
      slug: "scaling-laravel-no-rewrite",
      title: {
        pt: "Escalando Laravel sem reescrever: caching, queues, read models",
        en: "Scaling Laravel without rewrite: caching, queues, read models",
      },
      date: "2026-04-18",
      read: "16 min",
      kicker: { pt: "Infra", en: "Infrastructure" },
      summary: {
        pt: "Seu app ficou lento? Antes de reescrever em Go, tenta isso: cache em camadas, queues para jobs pesados, read models para queries complexas, índices no banco. 9 de 10 vezes você só precisa remover queries N+1 e cachear a homepage.",
        en: "App got slow? Before rewriting in Go, try this: layered caching, queues for heavy jobs, read models for complex queries, database indexes. 9 out of 10 times you just need to remove N+1 queries and cache the homepage.",
      },
      excerpt: {
        pt: "## O Mito da Reescrita\n\nSeu Laravel tá lento. Você quer reescrever em Go, Node, Rust.\n\n**Pare.**\n\n90% dos cases que vi, o problema não é Laravel — é:\n• Queries N+1\n• Sem cache de homepage\n• Processing síncrono de jobs pesados\n• Índices faltando no banco\n• Serialização ineficiente\n\n## Diagnóstico: Onde Você Tá Lento?\n\n### 1. Check N+1 Queries\n\n```php\n// ❌ ERRADO\n$users = User::all(); // 1 query\nforeach ($users as $user) {\n  echo $user->profile->bio; // 1 query por usuário\n}\n// Total: 1 + 101 queries para 100 usuários\n\n// ✅ CORRETO\n$users = User::with('profile')->get(); // 2 queries\nforeach ($users as $user) {\n  echo $user->profile->bio;\n}\n```\n\n**Como encontrar N+1:**\n• `php artisan debugbar` - QueryLogger mostra duplicatas\n• `DB::listen()` - log todas as queries em produção\n• Procure por queries idênticas em loops\n\n```php\nDB::listen(function ($query) {\n  if ($query->time > 50) { // Queries lentas\n    Log::warning('Slow query', [\n      'sql' => $query->sql,\n      'bindings' => $query->bindings,\n      'time' => $query->time,\n    ]);\n  }\n});\n```\n\n### 2. Profile com Blackfire\n\n```bash\nbrew install blackfire-agent\nblackfire-cli run curl https://seu-app.com\n```\n\n**Você verá:**\n• Função mais lenta\n• Chamadas repetidas\n• Tempo em DB vs PHP\n• Memory leaks\n\n## Estratégia 1: Caching em Camadas\n\n### Cache Level 1: HTTP Response (Browser)\n\n```php\n// resources/views/products/index.blade.php\n<meta http-equiv=\"cache-control\" content=\"max-age=3600\">\n\n// Laravel (middleware)\nRoute::middleware('cache:3600')->group(function () {\n  Route::get('/products', [ProductController::class, 'index']);\n});\n```\n\n### Cache Level 2: Application Cache (Redis)\n\n```php\n// app/Http/Controllers/ProductController.php\npublic function index()\n{\n  return Cache::remember('products.all', 3600, function () {\n    return Product::with('category')\n      ->select('id', 'name', 'price', 'category_id')\n      ->get();\n  });\n}\n\n// Quando atualizar um produto\npublic function update(Request $request, Product $product)\n{\n  $product->update($request->validated());\n  Cache::forget('products.all'); // Invalida cache\n  return redirect()->back();\n}\n```\n\n### Cache Level 3: Query Result Cache\n\n```php\n// app/Repositories/ProductRepository.php\npublic function getActivePriced()\n{\n  $key = 'products:active:priced';\n  $ttl = now()->addHours(1);\n  \n  return Cache::remember($key, $ttl, function () {\n    return Product::where('active', true)\n      ->whereNotNull('price')\n      ->select('id', 'name', 'price')\n      ->orderBy('name')\n      ->get();\n  });\n}\n```\n\n### Cache Level 4: Database Query Cache (Índices)\n\n```php\n// database/migrations/2026_04_18_add_indexes.php\nSchema::table('products', function (Blueprint $table) {\n  $table->index('active');\n  $table->index(['category_id', 'active']);\n  $table->index('created_at');\n  $table->fullText(['name', 'description']);\n});\n\n// Query agora é muito mais rápida\nProduct::whereActive(true)\n  ->whereCategory(5)\n  ->orderByDesc('created_at')\n  ->get();\n```\n\n## Estratégia 2: Async Processing com Queues\n\n### Problema: Requisição Bloqueada\n\n```php\n// ❌ ERRADO - Usuário espera\npublic function checkout(Request $request)\n{\n  $order = Order::create($request->validated());\n  \n  // Email leva 2 segundos\n  Mail::send(new OrderConfirmation($order));\n  \n  // PDF leva 3 segundos\n  $pdf = PDF::generate($order);\n  $order->update(['pdf_path' => $pdf]);\n  \n  // SMS leva 1 segundo\n  Twilio::send($order->customer->phone);\n  \n  return response()->json(['order' => $order]); // 6 segundos depois\n}\n```\n\n### Solução: Dispatch para Queues\n\n```php\n// ✅ CORRETO - Usuário vê resposta em 50ms\npublic function checkout(Request $request)\n{\n  $order = Order::create($request->validated());\n  \n  // Dispatch para background jobs\n  SendOrderConfirmation::dispatch($order);\n  GenerateOrderPDF::dispatch($order);\n  SendOrderSMS::dispatch($order);\n  \n  return response()->json([\n    'order' => $order,\n    'status' => 'processing',\n  ]); // Resposta imediata\n}\n\n// app/Jobs/SendOrderConfirmation.php\nclass SendOrderConfirmation implements ShouldQueue\n{\n  use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;\n  \n  public function __construct(public Order $order) {}\n  \n  public function handle()\n  {\n    Mail::send(new OrderConfirmation($this->order));\n  }\n}\n\n// app/Jobs/GenerateOrderPDF.php\nclass GenerateOrderPDF implements ShouldQueue\n{\n  use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;\n  \n  public function __construct(public Order $order) {}\n  \n  public function handle()\n  {\n    $pdf = PDF::generate($this->order);\n    $this->order->update(['pdf_path' => $pdf]);\n    \n    // Dispara outro job quando terminar\n    NotifySlackOrderReady::dispatch($this->order);\n  }\n}\n```\n\n### Configurar Redis + Supervisor\n\n```bash\n# .env\nQUEUE_CONNECTION=redis\nREDIS_HOST=127.0.0.1\nREDIS_PORT=6379\n\n# supervisord.conf\n[program:laravel-worker]\nprocess_name=%(program_name)s_%(process_num)02d\ncommand=php /path/to/artisan queue:work redis --sleep=3 --tries=3\nautostart=true\nnumprocs=4\nredirect_stderr=true\n```\n\n## Estratégia 3: Read Models (CQRS Light)\n\n### Problema: Queries Complexas\n\n```php\n// ❌ ERRADO - Calcula tudo em tempo real\npublic function dashboard()\n{\n  $totalSales = Order::whereMonth('created_at', now()->month)\n    ->sum('total');\n  \n  $topProducts = Order::with('items')\n    ->whereMonth('created_at', now()->month)\n    ->get()\n    ->flatMap->items\n    ->groupBy('product_id')\n    ->map(fn ($items) => [\n      'product_id' => $items->first()->product_id,\n      'quantity' => $items->count(),\n      'revenue' => $items->sum('price'),\n    ])\n    ->sortByDesc('revenue')\n    ->take(10);\n  \n  $customerMetrics = Customer::with('orders')\n    ->get()\n    ->map(fn ($customer) => [\n      'id' => $customer->id,\n      'name' => $customer->name,\n      'lifetime_value' => $customer->orders->sum('total'),\n      'order_count' => $customer->orders->count(),\n    ]);\n  \n  return view('dashboard', [\n    'totalSales' => $totalSales,\n    'topProducts' => $topProducts,\n    'customerMetrics' => $customerMetrics,\n  ]);\n}\n```\n\n### Solução: Pré-calcular em Read Model\n\n```php\n// database/migrations/2026_04_18_create_dashboard_metrics.php\nSchema::create('dashboard_metrics', function (Blueprint $table) {\n  $table->id();\n  $table->integer('year');\n  $table->integer('month');\n  $table->decimal('total_sales', 12, 2);\n  $table->integer('order_count');\n  $table->decimal('avg_order_value', 12, 2);\n  $table->timestamps();\n  $table->unique(['year', 'month']);\n});\n\nSchema::create('top_products_read_model', function (Blueprint $table) {\n  $table->id();\n  $table->foreignIdFor(Product::class);\n  $table->integer('year');\n  $table->integer('month');\n  $table->integer('quantity_sold');\n  $table->decimal('total_revenue', 12, 2);\n  $table->timestamps();\n  $table->unique(['product_id', 'year', 'month']);\n});\n\n// app/Jobs/RecalculateDashboardMetrics.php\nclass RecalculateDashboardMetrics implements ShouldQueue\n{\n  public function handle()\n  {\n    $month = now();\n    \n    // Calcula agregação pesada\n    $metrics = Order::whereYear('created_at', $month->year)\n      ->whereMonth('created_at', $month->month)\n      ->aggregate([\n        'total_sales' => DB::raw('SUM(total)'),\n        'order_count' => DB::raw('COUNT(*)')\n      ]);\n    \n    DashboardMetric::updateOrCreate(\n      ['year' => $month->year, 'month' => $month->month],\n      [\n        'total_sales' => $metrics->total_sales,\n        'order_count' => $metrics->order_count,\n        'avg_order_value' => $metrics->total_sales / $metrics->order_count,\n      ]\n    );\n  }\n}\n\n// Controller agora é trivial\npublic function dashboard()\n{\n  $metrics = DashboardMetric::whereYear('year', now()->year)\n    ->whereMonth('month', now()->month)\n    ->first();\n  \n  $topProducts = TopProductsReadModel::where('year', now()->year)\n    ->where('month', now()->month)\n    ->orderByDesc('total_revenue')\n    ->limit(10)\n    ->get();\n  \n  return view('dashboard', [\n    'metrics' => $metrics,\n    'topProducts' => $topProducts,\n  ]);\n}\n```\n\n## Estratégia 4: Índices Inteligentes\n\n```php\n// database/migrations/2026_04_18_optimize_indexes.php\n\nSchema::table('orders', function (Blueprint $table) {\n  // Queries por status + data\n  $table->index(['status', 'created_at']);\n  \n  // Queries por customer\n  $table->index('customer_id');\n  \n  // Sorting por updated_at\n  $table->index('updated_at');\n  \n  // Full-text search\n  $table->fullText(['reference_number', 'notes']);\n});\n\nSchema::table('customers', function (Blueprint $table) {\n  // Filtro por email (login, busca)\n  $table->unique('email');\n  \n  // Sorting\n  $table->index('created_at');\n});\n\nSchema::table('order_items', function (Blueprint $table) {\n  // JOINs rápidos\n  $table->index('order_id');\n  $table->index('product_id');\n});\n```\n\n**EXPLAIN ANALYZE**\n\n```php\n// Antes do índice: Full table scan (lento)\nDB::statement('EXPLAIN ANALYZE SELECT * FROM orders WHERE status = \"pending\" AND created_at > NOW() - INTERVAL 7 DAY');\n\n// Depois do índice: Index range scan (rápido)\n```\n\n## Estratégia 5: Serialização Eficiente\n\n```php\n// ❌ ERRADO - Carrega tudo\nRoute::get('/api/products', function () {\n  return Product::with('category', 'reviews', 'inventory')\n    ->get();\n  // Response: 2MB para 100 produtos\n});\n\n// ✅ CORRETO - Seleciona só o necessário\nRoute::get('/api/products', function () {\n  return Product::select('id', 'name', 'price', 'category_id')\n    ->with([\n      'category:id,name',\n      'reviews:id,product_id,rating',\n    ])\n    ->get();\n  // Response: 150KB para 100 produtos\n});\n```\n\n## Checklist de Performance\n\n**Imediato (antes de segunda-feira):**\n• Remover N+1 queries com `with()`\n• Usar `select()` para trazer só colunas necessárias\n• Adicionar índices nas colunas de `where` e `orderBy`\n• Cache da homepage com `Cache::remember()`\n\n**Curto prazo (semana que vem):**\n• Mover jobs síncronos para queues\n• Implementar read models para dashboards\n• Usar Redis para cache de sessão\n• Monitor com Blackfire/Debugbar\n\n**Médio prazo (próximo mês):**\n• Database replication (read replicas)\n• CDN para assets\n• Elasticsearch para buscas complexas\n• Horizontal scaling com load balancer\n\n## Quando Realmente Precisa Reescrever\n\n**Reescrever SÓ se:**\n• Laravel chega em 100K RPS e precisa de 200K\n• Latência sub-milissegundo (trading, gaming)\n• Problema é real-time (websockets 24/7)\n• Team prefere outra linguagem (não é decisão de perf)\n\n**Não é caso para reescrever:**\n• App lento mas sem medir\n• \"Go é mais rápido que PHP\"\n• Reimplementar do zero \"certo\"\n• Porque novo tech é legal\n\n## Resumo\n\n**90% do tempo, escalar Laravel é:**\n1. Encontrar gargalo com profiler\n2. Cache em 3 níveis (browser, app, db)\n3. Mover work sync → async com queues\n4. Read models para agregações\n5. Índices inteligentes no banco\n\n**Tempo**: 1-2 sprints\n**Custo**: 0 (usa infra que já tem)\n**Risco**: Baixo (mudanças incrementais)\n\nReescrever leva 6 meses, custa 3x mais, e você descobre que Node também tá lento sem cache.",
        en: "## The Rewrite Myth\n\nYour Laravel is slow. You want to rewrite in Go, Node, Rust.\n\n**Stop.**\n\n90% of cases I've seen, the problem isn't Laravel — it's:\n• N+1 queries\n• No homepage caching\n• Synchronous heavy processing\n• Missing database indexes\n• Inefficient serialization\n\n## Diagnosis: Where Are You Slow?\n\n### 1. Check N+1 Queries\n\n```php\n// ❌ WRONG\n$users = User::all(); // 1 query\nforeach ($users as $user) {\n  echo $user->profile->bio; // 1 query per user\n}\n// Total: 1 + 101 queries for 100 users\n\n// ✅ CORRECT\n$users = User::with('profile')->get(); // 2 queries\nforeach ($users as $user) {\n  echo $user->profile->bio;\n}\n```\n\n**How to find N+1:**\n• `php artisan debugbar` - QueryLogger shows duplicates\n• `DB::listen()` - log all queries in production\n• Look for identical queries in loops\n\n```php\nDB::listen(function ($query) {\n  if ($query->time > 50) { // Slow queries\n    Log::warning('Slow query', [\n      'sql' => $query->sql,\n      'bindings' => $query->bindings,\n      'time' => $query->time,\n    ]);\n  }\n});\n```\n\n### 2. Profile with Blackfire\n\n```bash\nbrew install blackfire-agent\nblackfire-cli run curl https://your-app.com\n```\n\n**You'll see:**\n• Slowest function\n• Repeated calls\n• Time in DB vs PHP\n• Memory leaks\n\n## Strategy 1: Layered Caching\n\n### Cache Level 1: HTTP Response (Browser)\n\n```php\n// resources/views/products/index.blade.php\n<meta http-equiv=\"cache-control\" content=\"max-age=3600\">\n\n// Laravel (middleware)\nRoute::middleware('cache:3600')->group(function () {\n  Route::get('/products', [ProductController::class, 'index']);\n});\n```\n\n### Cache Level 2: Application Cache (Redis)\n\n```php\n// app/Http/Controllers/ProductController.php\npublic function index()\n{\n  return Cache::remember('products.all', 3600, function () {\n    return Product::with('category')\n      ->select('id', 'name', 'price', 'category_id')\n      ->get();\n  });\n}\n\n// When updating a product\npublic function update(Request $request, Product $product)\n{\n  $product->update($request->validated());\n  Cache::forget('products.all'); // Invalidates cache\n  return redirect()->back();\n}\n```\n\n### Cache Level 3: Query Result Cache\n\n```php\n// app/Repositories/ProductRepository.php\npublic function getActivePriced()\n{\n  $key = 'products:active:priced';\n  $ttl = now()->addHours(1);\n  \n  return Cache::remember($key, $ttl, function () {\n    return Product::where('active', true)\n      ->whereNotNull('price')\n      ->select('id', 'name', 'price')\n      ->orderBy('name')\n      ->get();\n  });\n}\n```\n\n### Cache Level 4: Database Query Cache (Indexes)\n\n```php\n// database/migrations/2026_04_18_add_indexes.php\nSchema::table('products', function (Blueprint $table) {\n  $table->index('active');\n  $table->index(['category_id', 'active']);\n  $table->index('created_at');\n  $table->fullText(['name', 'description']);\n});\n\n// Query is now much faster\nProduct::whereActive(true)\n  ->whereCategory(5)\n  ->orderByDesc('created_at')\n  ->get();\n```\n\n## Strategy 2: Async Processing with Queues\n\n### Problem: Blocked Request\n\n```php\n// ❌ WRONG - User waits\npublic function checkout(Request $request)\n{\n  $order = Order::create($request->validated());\n  \n  // Email takes 2 seconds\n  Mail::send(new OrderConfirmation($order));\n  \n  // PDF takes 3 seconds\n  $pdf = PDF::generate($order);\n  $order->update(['pdf_path' => $pdf]);\n  \n  // SMS takes 1 second\n  Twilio::send($order->customer->phone);\n  \n  return response()->json(['order' => $order]); // 6 seconds later\n}\n```\n\n### Solution: Dispatch to Queues\n\n```php\n// ✅ CORRECT - User sees response in 50ms\npublic function checkout(Request $request)\n{\n  $order = Order::create($request->validated());\n  \n  // Dispatch to background jobs\n  SendOrderConfirmation::dispatch($order);\n  GenerateOrderPDF::dispatch($order);\n  SendOrderSMS::dispatch($order);\n  \n  return response()->json([\n    'order' => $order,\n    'status' => 'processing',\n  ]); // Immediate response\n}\n\n// app/Jobs/SendOrderConfirmation.php\nclass SendOrderConfirmation implements ShouldQueue\n{\n  use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;\n  \n  public function __construct(public Order $order) {}\n  \n  public function handle()\n  {\n    Mail::send(new OrderConfirmation($this->order));\n  }\n}\n\n// app/Jobs/GenerateOrderPDF.php\nclass GenerateOrderPDF implements ShouldQueue\n{\n  use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;\n  \n  public function __construct(public Order $order) {}\n  \n  public function handle()\n  {\n    $pdf = PDF::generate($this->order);\n    $this->order->update(['pdf_path' => $pdf]);\n    \n    // Dispatch another job when done\n    NotifySlackOrderReady::dispatch($this->order);\n  }\n}\n```\n\n### Configure Redis + Supervisor\n\n```bash\n# .env\nQUEUE_CONNECTION=redis\nREDIS_HOST=127.0.0.1\nREDIS_PORT=6379\n\n# supervisord.conf\n[program:laravel-worker]\nprocess_name=%(program_name)s_%(process_num)02d\ncommand=php /path/to/artisan queue:work redis --sleep=3 --tries=3\nautostart=true\nnumprocs=4\nredirect_stderr=true\n```\n\n## Strategy 3: Read Models (CQRS Light)\n\n### Problem: Complex Queries\n\n```php\n// ❌ WRONG - Calculates everything in real-time\npublic function dashboard()\n{\n  $totalSales = Order::whereMonth('created_at', now()->month)\n    ->sum('total');\n  \n  $topProducts = Order::with('items')\n    ->whereMonth('created_at', now()->month)\n    ->get()\n    ->flatMap->items\n    ->groupBy('product_id')\n    ->map(fn ($items) => [\n      'product_id' => $items->first()->product_id,\n      'quantity' => $items->count(),\n      'revenue' => $items->sum('price'),\n    ])\n    ->sortByDesc('revenue')\n    ->take(10);\n  \n  $customerMetrics = Customer::with('orders')\n    ->get()\n    ->map(fn ($customer) => [\n      'id' => $customer->id,\n      'name' => $customer->name,\n      'lifetime_value' => $customer->orders->sum('total'),\n      'order_count' => $customer->orders->count(),\n    ]);\n  \n  return view('dashboard', [\n    'totalSales' => $totalSales,\n    'topProducts' => $topProducts,\n    'customerMetrics' => $customerMetrics,\n  ]);\n}\n```\n\n### Solution: Pre-calculate in Read Model\n\n```php\n// database/migrations/2026_04_18_create_dashboard_metrics.php\nSchema::create('dashboard_metrics', function (Blueprint $table) {\n  $table->id();\n  $table->integer('year');\n  $table->integer('month');\n  $table->decimal('total_sales', 12, 2);\n  $table->integer('order_count');\n  $table->decimal('avg_order_value', 12, 2);\n  $table->timestamps();\n  $table->unique(['year', 'month']);\n});\n\nSchema::create('top_products_read_model', function (Blueprint $table) {\n  $table->id();\n  $table->foreignIdFor(Product::class);\n  $table->integer('year');\n  $table->integer('month');\n  $table->integer('quantity_sold');\n  $table->decimal('total_revenue', 12, 2);\n  $table->timestamps();\n  $table->unique(['product_id', 'year', 'month']);\n});\n\n// app/Jobs/RecalculateDashboardMetrics.php\nclass RecalculateDashboardMetrics implements ShouldQueue\n{\n  public function handle()\n  {\n    $month = now();\n    \n    // Calculates heavy aggregation\n    $metrics = Order::whereYear('created_at', $month->year)\n      ->whereMonth('created_at', $month->month)\n      ->aggregate([\n        'total_sales' => DB::raw('SUM(total)'),\n        'order_count' => DB::raw('COUNT(*)')\n      ]);\n    \n    DashboardMetric::updateOrCreate(\n      ['year' => $month->year, 'month' => $month->month],\n      [\n        'total_sales' => $metrics->total_sales,\n        'order_count' => $metrics->order_count,\n        'avg_order_value' => $metrics->total_sales / $metrics->order_count,\n      ]\n    );\n  }\n}\n\n// Controller is now trivial\npublic function dashboard()\n{\n  $metrics = DashboardMetric::whereYear('year', now()->year)\n    ->whereMonth('month', now()->month)\n    ->first();\n  \n  $topProducts = TopProductsReadModel::where('year', now()->year)\n    ->where('month', now()->month)\n    ->orderByDesc('total_revenue')\n    ->limit(10)\n    ->get();\n  \n  return view('dashboard', [\n    'metrics' => $metrics,\n    'topProducts' => $topProducts,\n  ]);\n}\n```\n\n## Strategy 4: Smart Indexes\n\n```php\n// database/migrations/2026_04_18_optimize_indexes.php\n\nSchema::table('orders', function (Blueprint $table) {\n  // Queries by status + date\n  $table->index(['status', 'created_at']);\n  \n  // Queries by customer\n  $table->index('customer_id');\n  \n  // Sorting by updated_at\n  $table->index('updated_at');\n  \n  // Full-text search\n  $table->fullText(['reference_number', 'notes']);\n});\n\nSchema::table('customers', function (Blueprint $table) {\n  // Filter by email (login, search)\n  $table->unique('email');\n  \n  // Sorting\n  $table->index('created_at');\n});\n\nSchema::table('order_items', function (Blueprint $table) {\n  // Fast JOINs\n  $table->index('order_id');\n  $table->index('product_id');\n});\n```\n\n**EXPLAIN ANALYZE**\n\n```php\n// Before index: Full table scan (slow)\nDB::statement('EXPLAIN ANALYZE SELECT * FROM orders WHERE status = \"pending\" AND created_at > NOW() - INTERVAL 7 DAY');\n\n// After index: Index range scan (fast)\n```\n\n## Strategy 5: Efficient Serialization\n\n```php\n// ❌ WRONG - Loads everything\nRoute::get('/api/products', function () {\n  return Product::with('category', 'reviews', 'inventory')\n    ->get();\n  // Response: 2MB for 100 products\n});\n\n// ✅ CORRECT - Select only what's needed\nRoute::get('/api/products', function () {\n  return Product::select('id', 'name', 'price', 'category_id')\n    ->with([\n      'category:id,name',\n      'reviews:id,product_id,rating',\n    ])\n    ->get();\n  // Response: 150KB for 100 products\n});\n```\n\n## Performance Checklist\n\n**Immediate (before Monday):**\n• Remove N+1 queries with `with()`\n• Use `select()` to fetch only necessary columns\n• Add indexes on `where` and `orderBy` columns\n• Cache homepage with `Cache::remember()`\n\n**Short term (next week):**\n• Move synchronous jobs to queues\n• Implement read models for dashboards\n• Use Redis for session cache\n• Monitor with Blackfire/Debugbar\n\n**Medium term (next month):**\n• Database replication (read replicas)\n• CDN for assets\n• Elasticsearch for complex searches\n• Horizontal scaling with load balancer\n\n## When You Actually Need to Rewrite\n\n**Rewrite ONLY if:**\n• Laravel reaches 100K RPS and needs 200K\n• Sub-millisecond latency required (trading, gaming)\n• Real-time problem (24/7 websockets)\n• Team prefers other language (not a perf decision)\n\n**NOT a case for rewriting:**\n• App is slow but unmeasured\n• \"Go is faster than PHP\"\n• Reimplementing from scratch \"correctly\"\n• Because new tech is cool\n\n## Summary\n\n**90% of the time, scaling Laravel is:**\n1. Find bottleneck with profiler\n2. Cache in 3 layers (browser, app, db)\n3. Move sync work → async with queues\n4. Read models for aggregations\n5. Smart indexes in database\n\n**Time**: 1-2 sprints\n**Cost**: 0 (use existing infra)\n**Risk**: Low (incremental changes)\n\nRewriting takes 6 months, costs 3x more, and you discover Node is also slow without caching.",
      },
    },
    {
      slug: "portfolio-project-ideas",
      title: {
        pt: "Projetos para portfólio: ideias além da calculadora",
        en: "Portfolio projects: ideas beyond the calculator",
      },
      date: "2026-04-19",
      read: "14 min",
      kicker: { pt: "Carreira", en: "Career" },
      summary: {
        pt: "Seu portfólio não impressiona ninguém com CRUD de notas ou calculadora. Ideia: cria algo que resolve seu problema real. Web scraper, analisador de GitHub, simulador, exportador de dados. O projeto de verdade não é aquele que funciona — é aquele que é honesto sobre suas limitações e desafios arquiteturais.",
        en: "Your portfolio won't impress anyone with a notes CRUD or calculator. Idea: build something that solves your real problem. Web scraper, GitHub analyzer, simulator, data exporter. The real project isn't the one that works — it's the one that's honest about its architectural challenges.",
      },
      excerpt: {
        pt: "## O Problema: Portfólios Genéricos\n\nVocê vê portfolios cheios de:\n• Todo app\n• Calculadora\n• CRUD de produtos\n• Blog com Markdown\n• Chat em tempo real\n\n**Ninguém diferencia disso.** Todo dev fez. Recrutador vê 50 desses por semana.\n\n## O Que Impressiona (De Verdade)\n\n### 1. Soluciona Seu Problema Real\n\n**Exemplos que funcionam:**\n\n```\n• Scraper que monitora preços de imóveis no seu bairro\n  → Envia alerta no Telegram quando cai abaixo de X\n  → Redux na sua vida, que dirá no código\n\n• Analisador de GitHub que extrai padrões de bugs\n  → Lê issues + PRs do teu repo\n  → Agrupa por tipo (memory leak, race condition, off-by-one)\n  → Gera relatório: \"Você cai 3x em boundary conditions\"\n\n• Simulador de filas com múltiplas estratégias\n  → Compara SJF vs Priority vs Fair Queueing\n  → Visualiza em tempo real qual é mais eficiente pra seu caso\n  → Exporta gráficos pro relatório\n\n• Exportador de dados pessoais\n  → Puxa historico do seu email, Google Drive, Telegram\n  → Reorganiza em timeline\n  → Gera \"seu ano em números\": quantas msgs, fotos, contribuições\n  → Cria um PDF bonito\n\n• Monitorizador de CI/CD customizado\n  → Hookeia GitHub Actions\n  → Classifica falhas (test, lint, build, deploy)\n  → Sugere quem deve revisar baseado em expertise\n  → Notifica no Slack com contexto\n```\n\n### 2. Mostra Trade-offs Arquiteturais\n\nO que diferencia devs sênior:\n\n```\n❌ FRACO: \"Funciona, é rápido, código lindo\"\n\n✅ FORTE:\n• \"Função X é lenta em 2% dos casos porque [motivo]\"\n• \"Comecei com Redis, mas descobri que [problema]\"\n• \"Usando Postgres JSONB aqui porque queries aninhadas iam matar perf\"\n• \"Troquei event sourcing por CQRS light porque [trade-off]\"\n• \"Cacheei agressivamente porque latência sub-100ms é crítica\"\n```\n\n**Projeto com histórico de decisões > projeto perfeito nascido pronto**\n\n## Categorias de Projetos Que Funcionam\n\n### Categoria A: Data + Scraping\n\n**Ideia 1: Scraper com análise**\n\n```php\n// Monitora preços de produtos no Mercado Livre / OLX\n// Cada produto tem histórico de preço\n// Alertas por Telegram: \"Queda 20% nos últimos 7 dias\"\n\nclass ProductMonitor\n{\n  public function scrapeAndAnalyze(): void\n  {\n    $products = $this->scraper->fetch();\n    \n    foreach ($products as $product) {\n      $history = PriceHistory::where('product_id', $product->id)\n        ->orderByDesc('checked_at')\n        ->limit(30)\n        ->get();\n      \n      $percentChange = $this->calculateTrend($history);\n      \n      if ($percentChange < -20) {\n        $this->notifyTelegram(\"Preço caiu {$percentChange}%: {$product->name}\");\n      }\n      \n      PriceHistory::create([\n        'product_id' => $product->id,\n        'price' => $product->price,\n        'checked_at' => now(),\n      ]);\n    }\n  }\n}\n```\n\n**Ideia 2: Analisador de repositório GitHub**\n\n```php\n// Puxa issues, PRs, commits do teu repo\n// Identifica padrões de bugs\n\nclass GitHubAnalyzer\n{\n  public function analyzeErrorPatterns(): array\n  {\n    $issues = $this->github->fetchIssues('vitorgabrieldev/laravel-fintech');\n    \n    $patterns = [];\n    foreach ($issues as $issue) {\n      // Classifica por tipo\n      if (str_contains($issue->title, ['null', 'undefined', 'NaN'])) {\n        $patterns['null-safety'][]= $issue;\n      }\n      if (str_contains($issue->body, ['race', 'concurrent', 'transaction'])) {\n        $patterns['concurrency'][] = $issue;\n      }\n      if (str_contains($issue->body, ['loop', 'iteration', 'index'])) {\n        $patterns['off-by-one'][] = $issue;\n      }\n    }\n    \n    return [\n      'total_issues' => count($issues),\n      'patterns' => $patterns,\n      'top_issue' => $this->getMostCommonPattern($patterns),\n      'recommendation' => \"Seu maior problema é {$patterns.top_issue}, considere...\",\n    ];\n  }\n}\n```\n\n### Categoria B: Simuladores e Visualizadores\n\n**Ideia 3: Simulador de filas**\n\n```php\n// Compara diferentes estratégias de escalonamento\n\nclass QueueSimulator\n{\n  public function compareStrategies(array $jobs): array\n  {\n    return [\n      'fifo' => $this->simulateFIFO($jobs),\n      'sjf' => $this->simulateSJF($jobs),\n      'priority' => $this->simulatePriority($jobs),\n      'fair_queueing' => $this->simulateFairQueueing($jobs),\n    ];\n  }\n  \n  private function simulateSJF(array $jobs): array\n  {\n    $sorted = collect($jobs)->sortBy('duration');\n    $totalWaitTime = 0;\n    $timeline = [];\n    \n    foreach ($sorted as $job) {\n      $totalWaitTime += $job->duration;\n      $timeline[] = [\n        'job' => $job->name,\n        'started_at' => $totalWaitTime - $job->duration,\n        'finished_at' => $totalWaitTime,\n      ];\n    }\n    \n    return [\n      'strategy' => 'Shortest Job First',\n      'avg_wait_time' => $totalWaitTime / count($jobs),\n      'timeline' => $timeline,\n    ];\n  }\n}\n```\n\n**Ideia 4: Visualizador de transações bancárias**\n\n```\n• Importa CSV do banco\n• Categoriza automaticamente (Alimentação, Transporte, etc)\n• Mostra gráficos: gastos por mês, categoria, dia da semana\n• Identifica anomalias: \"Você gastou 3x em Restaurant em Março\"\n• Prediz: \"Seu padrão de gastos = R$2.500/mês\"\n• Exporta insights em PDF\n```\n\n### Categoria C: Ferramentas Pessoais\n\n**Ideia 5: Exportador de dados pessoais**\n\n```php\n// Cria arquivo único com seu histórico de vida digital\n\nclass PersonalDataExporter\n{\n  public function export(): void\n  {\n    $timeline = [];\n    \n    // Gmail\n    $emails = $this->gmail->fetch();\n    foreach ($emails as $email) {\n      $timeline[] = [\n        'date' => $email->date,\n        'type' => 'email',\n        'data' => $email->subject,\n      ];\n    }\n    \n    // GitHub contributions\n    $commits = $this->github->fetchCommits();\n    foreach ($commits as $commit) {\n      $timeline[] = [\n        'date' => $commit->created_at,\n        'type' => 'contribution',\n        'data' => $commit->message,\n      ];\n    }\n    \n    // Telegram messages\n    $messages = $this->telegram->fetchMessages();\n    foreach ($messages as $msg) {\n      $timeline[] = [\n        'date' => $msg->date,\n        'type' => 'message',\n        'data' => $msg->text,\n      ];\n    }\n    \n    $sorted = collect($timeline)->sortBy('date');\n    \n    // Gera stats\n    $stats = [\n      'total_emails' => count($emails),\n      'total_commits' => count($commits),\n      'total_messages' => count($messages),\n      'date_range' => $sorted->first()['date'] . ' to ' . $sorted->last()['date'],\n      'busiest_month' => $this->getBusiestMonth($sorted),\n      'commits_per_day' => count($commits) / $sorted->count(),\n    ];\n    \n    $this->pdf->generate('annual-report.pdf', $stats, $sorted);\n  }\n}\n```\n\n### Categoria D: Análise e Monitoring\n\n**Ideia 6: Monitor de CI/CD inteligente**\n\n```php\n// Hookeia GitHub Actions, classifica falhas\n\nclass CIPipeline\n{\n  public function classifyFailure(array $log): array\n  {\n    $content = implode('\\n', $log);\n    \n    return match(true) {\n      str_contains($content, ['FAILED', 'AssertionError']) => [\n        'type' => 'test',\n        'severity' => 'critical',\n        'action' => 'Seu teste falhou',\n      ],\n      str_contains($content, ['syntax error', 'parse error']) => [\n        'type' => 'lint',\n        'severity' => 'blocker',\n        'action' => 'Erro de sintaxe, não vai passar',\n      ],\n      str_contains($content, ['Connection refused', 'timeout']) => [\n        'type' => 'infra',\n        'severity' => 'warning',\n        'action' => 'Problema de conexão (ephemeral?)',\n      ],\n      str_contains($content, ['FATAL', 'OOM', 'panic']) => [\n        'type' => 'runtime',\n        'severity' => 'critical',\n        'action' => 'App crashou',\n      ],\n      default => [\n        'type' => 'unknown',\n        'severity' => 'info',\n        'action' => 'Falha desconhecida, inspeciona logs',\n      ]\n    };\n  }\n}\n```\n\n## Checklist: Seu Projeto Impressiona?\n\n**Responde SIM a:**\n\n• Resolveu um problema real seu (ou de alguém)\n• Tem um histórico de decisões documentadas\n• Mostra trade-offs: \"Usei Redis aqui porque X, mas Y é problema\"\n• Tem dados de verdade (não fake data)\n• Documenta limitações: \"Scaler pra 100K items é problema\"\n• Mostra iteração: \"Comecei com Y, mudei pra Z porque\"\n\n**Evita:**\n\n• \"Built with React, Firebase, Tailwind\" (genérico)\n• Código perfeito mas sem história\n• Feature creep (1.000 features, nenhuma bem feita)\n• Sem documentação de desafios\n• Tutorial-driven (copiou do YouTube)\n\n## Exemplo: Risklog (Meu)\n\nPor que impressiona:\n\n```\n✅ Problema real: Deploy silencioso é risco\n✅ Trade-off: Analisar diff é pesado, mas cacheamos resultados\n✅ Limitação honesta: Não detecta race conditions em runtime\n✅ Métrica: Reduziu post-deploy scrambles 62%\n✅ Arquitetura: Event stream de diffs → classificação → score\n✅ Decisão documentada: Elegemos Postgres JSONB porque queries aninhadas\n```\n\n## Próximos Passos\n\n**Semana 1:** Escolhe um problema seu\n**Semana 2-4:** Implementa solução básica (funciona, não perfeito)\n**Semana 5:** Documenta desafios: \"Por quê fiz assim?\"\n**Semana 6:** Mostra no README:\n• O problema\n• Sua solução\n• Trade-offs\n• Limitações\n• Como você iteraria\n\n**Resultado:** Portfólio que diz \"eu penso sobre arquitetura\", não \"eu sigo tutoriais\".",
        en: "## The Problem: Generic Portfolios\n\nYou see portfolios full of:\n• Todo app\n• Calculator\n• Product CRUD\n• Blog with Markdown\n• Real-time chat\n\n**No one differentiates from this.** Every dev did it. Recruiter sees 50 of these per week.\n\n## What Actually Impresses\n\n### 1. Solves Your Real Problem\n\n**Examples that work:**\n\n```\n• Scraper that monitors real estate prices in your neighborhood\n  → Sends Telegram alert when below X\n  → Solves your actual life problem, not a tutorial\n\n• GitHub analyzer that extracts bug patterns\n  → Reads issues + PRs from your repo\n  → Groups by type (memory leak, race condition, off-by-one)\n  → Report: \"You fall 3x into boundary conditions\"\n\n• Queue simulator with multiple strategies\n  → Compares SJF vs Priority vs Fair Queueing\n  → Visualizes real-time which is most efficient for your case\n  → Exports charts for report\n\n• Personal data exporter\n  → Pulls history from email, Google Drive, Telegram\n  → Reorganizes into timeline\n  → Generates \"your year in numbers\": messages, photos, contributions\n  → Creates beautiful PDF\n\n• Custom CI/CD monitor\n  → Hooks GitHub Actions\n  → Classifies failures (test, lint, build, deploy)\n  → Suggests who should review based on expertise\n  → Notifies Slack with context\n```\n\n### 2. Shows Architectural Trade-offs\n\nWhat differentiates senior devs:\n\n```\n❌ WEAK: \"Works, it's fast, code is clean\"\n\n✅ STRONG:\n• \"Function X is slow in 2% of cases because [reason]\"\n• \"Started with Redis, discovered [problem]\"\n• \"Using Postgres JSONB because nested queries would kill perf\"\n• \"Switched from event sourcing to CQRS light because [trade-off]\"\n• \"Aggressively cached because sub-100ms latency is critical\"\n```\n\n**Project with decision history > perfect project born perfect**\n\n## Categories of Working Projects\n\n### Category A: Data + Scraping\n\n**Idea 1: Scraper with analysis**\n\n```php\n// Monitors product prices on Mercado Livre / OLX\n// Each product has price history\n// Alerts via Telegram: \"20% drop in last 7 days\"\n\nclass ProductMonitor\n{\n  public function scrapeAndAnalyze(): void\n  {\n    $products = $this->scraper->fetch();\n    \n    foreach ($products as $product) {\n      $history = PriceHistory::where('product_id', $product->id)\n        ->orderByDesc('checked_at')\n        ->limit(30)\n        ->get();\n      \n      $percentChange = $this->calculateTrend($history);\n      \n      if ($percentChange < -20) {\n        $this->notifyTelegram(\"Price dropped {$percentChange}%: {$product->name}\");\n      }\n      \n      PriceHistory::create([\n        'product_id' => $product->id,\n        'price' => $product->price,\n        'checked_at' => now(),\n      ]);\n    }\n  }\n}\n```\n\n**Idea 2: GitHub repository analyzer**\n\n```php\n// Pulls issues, PRs, commits from your repo\n// Identifies bug patterns\n\nclass GitHubAnalyzer\n{\n  public function analyzeErrorPatterns(): array\n  {\n    $issues = $this->github->fetchIssues('vitorgabrieldev/laravel-fintech');\n    \n    $patterns = [];\n    foreach ($issues as $issue) {\n      // Classifies by type\n      if (str_contains($issue->title, ['null', 'undefined', 'NaN'])) {\n        $patterns['null-safety'][] = $issue;\n      }\n      if (str_contains($issue->body, ['race', 'concurrent', 'transaction'])) {\n        $patterns['concurrency'][] = $issue;\n      }\n      if (str_contains($issue->body, ['loop', 'iteration', 'index'])) {\n        $patterns['off-by-one'][] = $issue;\n      }\n    }\n    \n    return [\n      'total_issues' => count($issues),\n      'patterns' => $patterns,\n      'top_issue' => $this->getMostCommonPattern($patterns),\n      'recommendation' => \"Your biggest problem is {$patterns.top_issue}, consider...\",\n    ];\n  }\n}\n```\n\n### Category B: Simulators and Visualizers\n\n**Idea 3: Queue simulator**\n\n```php\n// Compares different scheduling strategies\n\nclass QueueSimulator\n{\n  public function compareStrategies(array $jobs): array\n  {\n    return [\n      'fifo' => $this->simulateFIFO($jobs),\n      'sjf' => $this->simulateSJF($jobs),\n      'priority' => $this->simulatePriority($jobs),\n      'fair_queueing' => $this->simulateFairQueueing($jobs),\n    ];\n  }\n  \n  private function simulateSJF(array $jobs): array\n  {\n    $sorted = collect($jobs)->sortBy('duration');\n    $totalWaitTime = 0;\n    $timeline = [];\n    \n    foreach ($sorted as $job) {\n      $totalWaitTime += $job->duration;\n      $timeline[] = [\n        'job' => $job->name,\n        'started_at' => $totalWaitTime - $job->duration,\n        'finished_at' => $totalWaitTime,\n      ];\n    }\n    \n    return [\n      'strategy' => 'Shortest Job First',\n      'avg_wait_time' => $totalWaitTime / count($jobs),\n      'timeline' => $timeline,\n    ];\n  }\n}\n```\n\n**Idea 4: Bank transaction visualizer**\n\n```\n• Imports bank CSV\n• Auto-categorizes (Food, Transport, etc)\n• Shows charts: spending by month, category, day of week\n• Identifies anomalies: \"You spent 3x on restaurants in March\"\n• Predicts: \"Your pattern = R$2,500/month\"\n• Exports insights to PDF\n```\n\n### Category C: Personal Tools\n\n**Idea 5: Personal data exporter**\n\n```php\n// Creates single file with your digital life history\n\nclass PersonalDataExporter\n{\n  public function export(): void\n  {\n    $timeline = [];\n    \n    // Gmail\n    $emails = $this->gmail->fetch();\n    foreach ($emails as $email) {\n      $timeline[] = [\n        'date' => $email->date,\n        'type' => 'email',\n        'data' => $email->subject,\n      ];\n    }\n    \n    // GitHub contributions\n    $commits = $this->github->fetchCommits();\n    foreach ($commits as $commit) {\n      $timeline[] = [\n        'date' => $commit->created_at,\n        'type' => 'contribution',\n        'data' => $commit->message,\n      ];\n    }\n    \n    // Telegram messages\n    $messages = $this->telegram->fetchMessages();\n    foreach ($messages as $msg) {\n      $timeline[] = [\n        'date' => $msg->date,\n        'type' => 'message',\n        'data' => $msg->text,\n      ];\n    }\n    \n    $sorted = collect($timeline)->sortBy('date');\n    \n    // Generate stats\n    $stats = [\n      'total_emails' => count($emails),\n      'total_commits' => count($commits),\n      'total_messages' => count($messages),\n      'date_range' => $sorted->first()['date'] . ' to ' . $sorted->last()['date'],\n      'busiest_month' => $this->getBusiestMonth($sorted),\n      'commits_per_day' => count($commits) / $sorted->count(),\n    ];\n    \n    $this->pdf->generate('annual-report.pdf', $stats, $sorted);\n  }\n}\n```\n\n### Category D: Analysis and Monitoring\n\n**Idea 6: Smart CI/CD monitor**\n\n```php\n// Hooks GitHub Actions, classifies failures\n\nclass CIPipeline\n{\n  public function classifyFailure(array $log): array\n  {\n    $content = implode('\\n', $log);\n    \n    return match(true) {\n      str_contains($content, ['FAILED', 'AssertionError']) => [\n        'type' => 'test',\n        'severity' => 'critical',\n        'action' => 'Your test failed',\n      ],\n      str_contains($content, ['syntax error', 'parse error']) => [\n        'type' => 'lint',\n        'severity' => 'blocker',\n        'action' => 'Syntax error, won\\'t pass',\n      ],\n      str_contains($content, ['Connection refused', 'timeout']) => [\n        'type' => 'infra',\n        'severity' => 'warning',\n        'action' => 'Connection problem (ephemeral?)',\n      ],\n      str_contains($content, ['FATAL', 'OOM', 'panic']) => [\n        'type' => 'runtime',\n        'severity' => 'critical',\n        'action' => 'App crashed',\n      ],\n      default => [\n        'type' => 'unknown',\n        'severity' => 'info',\n        'action' => 'Unknown failure, inspect logs',\n      ]\n    };\n  }\n}\n```\n\n## Checklist: Does Your Project Impress?\n\n**Answer YES to:**\n\n• Solved a real problem (yours or someone\\'s)\n• Has documented decision history\n• Shows trade-offs: \"Used Redis here because X, but Y is a problem\"\n• Has real data (not fake data)\n• Documents limitations: \"Scaling to 100K items is a problem\"\n• Shows iteration: \"Started with Y, changed to Z because\"\n\n**Avoid:**\n\n• \"Built with React, Firebase, Tailwind\" (generic)\n• Perfect code but no story\n• Feature creep (1,000 features, none well done)\n• No documentation of challenges\n• Tutorial-driven (copied from YouTube)\n\n## Example: Risklog (Mine)\n\nWhy it impresses:\n\n```\n✅ Real problem: Silent deploy is risky\n✅ Trade-off: Analyzing diff is heavy, but we cache results\n✅ Honest limitation: Doesn\\'t detect runtime race conditions\n✅ Metric: Reduced post-deploy scrambles 62%\n✅ Architecture: Event stream of diffs → classification → score\n✅ Documented decision: Chose Postgres JSONB because nested queries would kill perf\n```\n\n## Next Steps\n\n**Week 1:** Pick a problem you have\n**Week 2-4:** Build basic solution (works, not perfect)\n**Week 5:** Document challenges: \"Why did I do this?\"\n**Week 6:** Show in README:\n• The problem\n• Your solution\n• Trade-offs\n• Limitations\n• How you\\'d iterate\n\n**Result:** Portfolio that says \"I think about architecture\", not \"I follow tutorials\".",
      },
    },
  ],

  playground: [
    {
      title: "Bezier playground",
      kind: "canvas",
      note: "Drag handles, read the easing curve.",
    },
    {
      title: "Tokenizer viewer",
      kind: "widget",
      note: "Paste text, inspect BPE tokens live.",
    },
    {
      title: "CI/CD graph",
      kind: "graph",
      note: "Animated pipeline runs with risk tags.",
    },
  ],

  oss: [
    {
      repo: "laravel-fintech-core",
      owner: "vitorgabrieldev",
      desc: {
        pt: "Core bancário com ledger de partidas dobradas, contas multi-tenant e transações auditáveis.",
        en: "Banking core with double-entry ledger, multi-tenant accounts and auditable transactions.",
      },
      stars: 42,
      lang: "PHP",
      kind: { pt: "Autor", en: "Author" },
    },
    {
      repo: "risklog",
      owner: "vitorgabrieldev",
      desc: {
        pt: "Camada de CI/CD que resume deploys em linguagem natural — o que quebrou, por quê, quem deve olhar.",
        en: "CI/CD layer that summarises deploys in natural language — what broke, why, who should look.",
      },
      stars: 18,
      lang: "TypeScript",
      kind: { pt: "Autor", en: "Author" },
    },
    {
      repo: "matetatica-web",
      owner: "vitorgabrieldev",
      desc: {
        pt: "Plataforma de ensino para matemática adaptativa — motor de exercícios + repetição espaçada.",
        en: "Teaching platform for adaptive math — exercise engine + spaced repetition.",
      },
      stars: 11,
      lang: "Laravel",
      kind: { pt: "Autor", en: "Author" },
    },
    {
      repo: "laravel/framework",
      owner: "laravel",
      desc: {
        pt: "Pequenos fixes e PRs de docs upstream — type hints, casos extremos do query builder.",
        en: "Small fixes and docs PRs upstream — type hints, query builder edge cases.",
      },
      stars: null,
      lang: "PHP",
      kind: { pt: "Contribuidor", en: "Contributor" },
    },
    {
      repo: "spatie/laravel-permission",
      owner: "spatie",
      desc: {
        pt: "Bugfix para invalidação de cache de permissão com escopo de time em setups multi-guard.",
        en: "Bugfix for team-scoped permission cache invalidation in multi-guard setups.",
      },
      stars: null,
      lang: "PHP",
      kind: { pt: "Contribuidor", en: "Contributor" },
    },
    {
      repo: "dotfiles",
      owner: "vitorgabrieldev",
      desc: {
        pt: "Meu config de neovim + tmux + zsh. Nada revolucionário, só honesto.",
        en: "My neovim + tmux + zsh config. Nothing revolutionary, just honest.",
      },
      stars: 7,
      lang: "Lua",
      kind: { pt: "Autor", en: "Author" },
    },
  ],
};
