/* Shared data — projects, timeline, skills.
   Translatable fields use {pt, en} objects — read with window.td(field). */
window.PORTFOLIO_DATA = {
  meta: {
    name: "Vitor Gabriel de Oliveira",
    role: "Full Stack Engineer",
    location: "Londrina, BR",
    tz: "UTC−3",
    email: "contact@vitorgabriel.dev",
    whatsapp: "+55 43 98487-3807",
    github: "vitorgabrieldev",
  },

  projects: [
    {
      id: "laravel-fintech",
      name: "Laravel Fintech Core",
      year: "2025",
      category: { pt: "Plataforma Fintech", en: "Fintech Platform" },
      role: { pt: "Engenheiro Líder", en: "Lead Engineer" },
      stack: ["Laravel", "PostgreSQL", "Redis", "Docker"],
      summary: { pt: "Core bancário com ledger, transações e contas multi-tenant. Foco em garantias de consistência e throughput.", en: "Banking core with ledger, transactions and multi-tenant accounts. Focus on consistency guarantees and throughput." },
      impact: { pt: "Assentei a fundação: ledger de partidas dobradas, transações auditáveis, multi-tenancy com isolamento por schema. Core que suporta crescimento.", en: "I built the foundation: double-entry ledger, auditable transactions, multi-tenant schema isolation. Core that supports growth." },
      url: "https://github.com/vitorgabrieldev/laravel-fintech-core",
      accent: "#c96442",
      featured: true,
    },
    {
      id: "risklog",
      name: "Risklog",
      year: "2025",
      category: { pt: "Inteligência de Deploy", en: "Deployment Intelligence" },
      role: { pt: "Full Stack", en: "Full Stack" },
      stack: ["Laravel", "CI/CD", "GitHub Actions"],
      summary: { pt: "Integração CI/CD que rastreia risco por deploy, resumindo mudanças, donos e provável raio de blast.", en: "CI/CD integration that tracks risk per deploy, summarising changes, owners and probable blast radius." },
      impact: { pt: "O time adotou como checklist de release — menos surpresas após deploys.", en: "Team adopted it as a release checklist — fewer surprises after deploys." },
      url: "https://github.com/vitorgabrieldev/risklog-api",
      accent: "#6b7a4a",
      featured: true,
    },
    {
      id: "dubflow",
      name: "DubFlow",
      year: "2024",
      category: { pt: "Plataforma Social", en: "Social Platform" },
      role: { pt: "Full Stack", en: "Full Stack" },
      stack: ["Laravel", "Next.js", "TypeScript"],
      summary: { pt: "Plataforma comunitária para dubladores — casting, portfólio, mensagens diretas.", en: "Community platform for voice-over professionals — casting, portfolio, direct messages." },
      impact: { pt: "Entregue de ponta a ponta: API, auth, frontend, pipeline de deploy.", en: "Shipped end-to-end: API, auth, frontend, deploy pipeline." },
      url: "https://github.com/vitorgabrieldev/dubflow.pro.br",
      accent: "#8a5a8c",
      featured: true,
    },
    {
      id: "trabalho-amigo",
      name: "Trabalho Amigo",
      year: "2025",
      category: { pt: "Marketplace SaaS", en: "SaaS Marketplace" },
      role: { pt: "Full Stack", en: "Full Stack" },
      stack: ["Laravel", "Next.js", "PostgreSQL", "Stripe", "Docker"],
      summary: { pt: "Marketplace que conecta pessoas que precisam de serviços a profissionais locais — desde limpeza até design e tecnologia.", en: "Marketplace connecting service seekers with local professionals — from cleaning to design and tech." },
      impact: { pt: "Plataforma completa com fluxo de pagamento protegido, 2FA, busca inteligente com FTS, chat em tempo real e gestão de serviços.", en: "Full platform with secure payments, 2FA, intelligent search (FTS), real-time messaging, and service management." },
      url: "https://github.com/vitorgabrieldev/trabalhoamigo.com.br",
      accent: "#2d8a6e",
      featured: true,
    },
    {
      id: "pett-love",
      name: "Pett Love",
      year: "2024",
      category: { pt: "Frontend · SPA", en: "Frontend · SPA" },
      role: { pt: "Frontend", en: "Frontend" },
      stack: ["React", "TypeScript", "Tailwind", "Vite"],
      summary: { pt: "Interface moderna e responsiva para plataforma de pet care — com rotas dinâmicas, animações fluidas e design system robusto.", en: "Modern responsive interface for pet care platform — with dynamic routing, smooth animations and solid design system." },
      impact: { pt: "Implementei layout completo, interações e foi deployada em Vercel com builds otimizados.", en: "Shipped complete layout, interactions and deployed on Vercel with optimized builds." },
      url: "https://github.com/vitorgabrieldev/Pett-Love",
      accent: "#e67e22",
      featured: false,
    },
    {
      id: "terminal-simulator",
      name: "Terminal Simulator",
      year: "2024",
      category: { pt: "Ferramenta · Experimental", en: "Tool · Experimental" },
      role: { pt: "Full Stack", en: "Full Stack" },
      stack: ["React", "Vite", "TypeScript"],
      summary: { pt: "Simulador interativo de terminal com comandos reais — explore bash num navegador sem risco.", en: "Interactive terminal simulator with real commands — explore bash in a browser safely." },
      impact: { pt: "Explorei React puro, renderização de conteúdo dinâmico e experiência de usuário style terminal.", en: "Explored vanilla React, dynamic content rendering, and terminal-style UX." },
      url: "https://github.com/vitorgabrieldev/terminal-simulator",
      accent: "#16a34a",
      featured: false,
    },
    {
      id: "immortal-scrollytelling",
      name: "What would it be like to be immortal?",
      year: "2024",
      category: { pt: "Storytelling · Interativo", en: "Storytelling · Interactive" },
      role: { pt: "Full Stack", en: "Full Stack" },
      stack: ["React", "Tailwind", "GSAP", "Lenis", "Vite"],
      summary: { pt: "Scrollytelling imersivo sobre a jornada de um ser humano imortal — narrativa visual com animações sincronizadas ao scroll.", en: "Immersive scrollytelling about an immortal human's journey — visual narrative with scroll-synced animations." },
      impact: { pt: "Criei uma experiência interativa única explorando GSAP, smooth scroll com Lenis, e efeitos de partículas com TsParticles.", en: "Built unique interactive experience exploring GSAP animations, smooth scrolling, and particle effects." },
      url: "https://github.com/vitorgabrieldev/What-would-it-be-like-to-be-immortal",
      accent: "#8b5cf6",
      featured: false,
    },
    {
      id: "general-agent",
      name: "General Agent Terminal",
      year: "2025",
      category: { pt: "IA · Linux", en: "AI · Linux" },
      role: { pt: "Experimental", en: "Experimental" },
      stack: ["Python", "Mistral", "Linux"],
      summary: { pt: "Agente terminal com Mistral que raciocina sobre ações de shell antes de executá-las.", en: "Mistral-powered terminal agent that reasons about shell actions before executing them." },
      impact: { pt: "Protótipo de pesquisa pessoal — explorando workflows de sysadmin guiados por LLM.", en: "Personal research prototype — exploring LLM-driven sysadmin workflows." },
      url: "https://github.com/vitorgabrieldev/general-agent-terminal-linux",
      accent: "#3d5a7a",
      featured: false,
    },
    {
      id: "blockchain",
      name: "Blockchain Prototypes",
      year: "2024",
      category: { pt: "Blockchain", en: "Blockchain" },
      role: { pt: "Pesquisador", en: "Researcher" },
      stack: ["Solidity", "Ethereum", "Node.js"],
      summary: { pt: "Experimentos com DApps, lógica de chain customizada e consenso — validando integrações descentralizadas.", en: "Experiments with DApps, custom chain logic and consensus — validating decentralised integrations." },
      impact: { pt: "Aprofundei conhecimento em EVM, assinaturas e trade-offs on-chain vs off-chain.", en: "Gained depth on EVM, signatures and on-chain vs off-chain trade-offs." },
      url: "https://github.com/vitorgabrieldev/Blockchain",
      accent: "#b58844",
      featured: false,
    },
    {
      id: "motion-recognition",
      name: "Hand Motion Recognition",
      year: "2024",
      category: { pt: "Visão Computacional", en: "Computer Vision" },
      role: { pt: "Full Stack", en: "Full Stack" },
      stack: ["Python", "OpenCV"],
      summary: { pt: "Interface de gestos manuais em tempo real para otimização de interação.", en: "Real-time hand gesture interface for interaction optimisation." },
      impact: { pt: "Explorei pipelines de CV e processamento de vídeo de baixa latência em hardware comum.", en: "Explored CV pipelines and low-latency video processing on commodity hardware." },
      url: "https://github.com/vitorgabrieldev/motion-recognition-for-interaction-optimization",
      accent: "#4a7a6b",
      featured: false,
    },
    {
      id: "rotina",
      name: "Rotina",
      year: "2024",
      category: { pt: "Ferramentas Internas", en: "Internal Tools" },
      role: { pt: "Full Stack", en: "Full Stack" },
      stack: ["Laravel", "PHP"],
      summary: { pt: "Plataforma de organização empresarial — cadência semanal, ownership, bloqueios.", en: "Business organisation platform — weekly cadence, ownership, blockers." },
      impact: { pt: "Substituiu 3 planilhas para um time pequeno.", en: "Replaced 3 spreadsheets for a small team." },
      url: "https://github.com/vitorgabrieldev/rotina.pro.br",
      accent: "#7a5a4a",
      featured: false,
    },
    {
      id: "painel-startup",
      name: "Risklog Admin Panel",
      year: "2024",
      category: { pt: "Painel Administrativo", en: "Admin Dashboard" },
      role: { pt: "Full Stack", en: "Full Stack" },
      stack: ["Laravel", "Blade", "Tailwind"],
      summary: { pt: "Console de operações para o Risklog — deploys, usuários, limites de política.", en: "Operations console for Risklog — deploys, users, policy thresholds." },
      impact: { pt: "Deu ao time de ops controle direto sem precisar de mão de obra de engenharia.", en: "Gave the ops team direct control without engineering hand-offs." },
      url: "https://github.com/vitorgabrieldev/painel.startup.dev.br",
      accent: "#5a4a7a",
      featured: false,
    },
  ],

  timeline: [
    {
      year: "2026",
      company: "Clickweb",
      role: { pt: "Full Stack Pleno · Projetos", en: "Full Stack Pleno · Projects" },
      where: "Londrina, BR",
      current: true,
      stack: ["Laravel", "PostgreSQL", "Docker", "Kubernetes", "CI/CD", "React"],
      notes: { pt: "Liderança técnica nas principais entregas. Arquitetura, DevOps, mentoria.", en: "Ownership of technical direction on key deliveries. Architecture, DevOps, mentoring." },
    },
    {
      year: "2024",
      company: "Matetática",
      role: { pt: "Full Stack (TI)", en: "Full Stack (IT)" },
      where: "Londrina, BR",
      stack: ["Laravel", "React", "PostgreSQL", "Docker", "Node.js"],
      notes: { pt: "Plataforma de tutoria em matemática — do início ao fim, da API Laravel ao frontend React e deploy.", en: "Platform for math tutoring — end-to-end from Laravel API to React frontend and deploy." },
    },
    {
      year: "2024",
      company: "Clickweb",
      role: { pt: "Full Stack Junior", en: "Full Stack Junior" },
      where: "Londrina, BR",
      stack: ["Laravel", "React", "Docker", "Nginx", "PostgreSQL"],
      notes: { pt: "Promovido de estágio. Responsabilidades ampliadas em infra, Laravel e front-end.", en: "Promoted from intern. Extended responsibilities across infra, Laravel and front-end." },
    },
    {
      year: "2023",
      company: "Clickweb",
      role: { pt: "Estagiário Full Stack", en: "Full Stack Intern" },
      where: "Londrina, BR",
      stack: ["Laravel", "PHP", "JavaScript", "MySQL"],
      notes: { pt: "Primeiro cargo profissional. Aprendi disciplina de produção, fluxo de suporte, cadência de release.", en: "First professional role. Learned production discipline, support flow, release cadence." },
    },
    {
      year: "2022",
      company: "Marista Escola Social Irmão Acácio",
      role: { pt: "Ensino Médio Técnico em Informática para Internet", en: "Technical High School · Computer Science for the Web" },
      where: "Londrina, BR",
      stack: ["HTML", "CSS", "JavaScript", "Networks", "Linux"],
      notes: { pt: "Ensino médio técnico — fundamentos de CS, redes e desenvolvimento web.", en: "Technical high-school — foundations in CS, networks, and web development." },
    },
  ],

  skills: {
    "Backend": ["Laravel", "PHP", "Node.js", "Express", "Apollo", "GraphQL", "REST", "MongoDB", "PostgreSQL", "JWT", "PM2"],
    "Frontend": ["React", "Next.js", "TypeScript", "Vue", "Angular", "Tailwind", "SASS/SCSS", "jQuery"],
    "Infra / DevOps": ["Docker", "Kubernetes", "CI/CD", "GitHub Actions", "Nginx", "Linux", "DigitalOcean", "AWS"],
    "Exploratory": ["Solidity", "Ethereum", "LLMs (Mistral/OpenAI)", "Computer Vision"],
  },

  journal: [
    {
      slug: "ledger-consistency",
      title: { pt: "Por que seu ledger precisa de partidas dobradas desde o início", en: "Why your ledger needs double-entry, even on day one" },
      date: "2026-03-14",
      read: "7 min",
      kicker: { pt: "Arquitetura", en: "Architecture" },
      excerpt: { pt: "Partidas dobradas não são opcionais. Cada débito exige um crédito, cada transação cria dois registros. Implementar cedo custa 2 horas. Retrofitar em produção custa 200 horas + reconciliações manuais. Nota do Laravel Fintech Core.", en: "Double-entry isn't optional. Every debit demands a credit, every transaction creates two records. Implementing early costs 2 hours. Retrofitting in production costs 200 hours + manual reconciliations. A note from Laravel Fintech Core." },
    },
    {
      slug: "risklog-post",
      title: { pt: "Entregando o Risklog: transformando deploys em parágrafos", en: "Shipping Risklog: turning deploys into paragraphs" },
      date: "2026-02-02",
      read: "5 min",
      kicker: { pt: "Estudo de caso", en: "Case study" },
      excerpt: { pt: "Deploy silencioso é deploy arriscado. Risklog analisa cada diff, classifica por risco (migration, auth, infra, UI), pondera por churn, pontua. O resultado é um parágrafo legível no Slack: \"2 migrations, auth layer rewritten, 1 reviewer. Risk: MEDIUM.\" Reduced post-deploy scrambles by 62%.", en: "Silent deploy is risky deploy. Risklog analyzes each diff, classifies by risk (migration, auth, infra, UI), weights by churn, scores. Output: one readable paragraph in Slack: \"2 migrations, auth layer rewritten, 1 reviewer. Risk: MEDIUM.\" Reduced post-deploy scrambles by 62%." },
    },
    {
      slug: "kv-attention",
      title: { pt: "Atenção do zero: notas lendo o paper do GPT", en: "Attention from scratch: notes while reading the GPT paper" },
      date: "2025-12-20",
      read: "11 min",
      kicker: { pt: "Aprendendo em público", en: "Learning in public" },
      excerpt: { pt: "Implementei um transformer de scratch em PHP. Tokenização BPE, embedding de posição, Q/K/V attention, feed-forward MLP. O 'insight': atenção é apenas matrix multiplication. O código cabe em 200 linhas. A matemática é belíssima — como você constrói inteligência a partir de multiplicação de matrizes.", en: "I built a transformer from scratch in PHP. BPE tokenisation, positional embedding, Q/K/V attention, feed-forward MLP. The insight: attention is just matrix multiplication. Code fits in 200 lines. The math is beautiful — how you build intelligence from linear algebra." },
    },
    {
      slug: "laravel-tenancy",
      title: { pt: "Multi-tenancy no Laravel: quatro formas, uma armadilha", en: "Multi-tenancy in Laravel: four shapes, one trap" },
      date: "2025-11-11",
      read: "8 min",
      kicker: { pt: "Arquitetura", en: "Architecture" },
      excerpt: { pt: "Database per tenant: isolamento máximo, complexidade máxima. Schema per tenant: melhor custo-benefício. Row-scoped: barato, mas todo query carrega tenant_id (armadilha: sem índice, é slow). Column-scoped: nunca use. A regra: comece simples, migre quando precisa. Tenant atual exige schema per tenant + read models separados.", en: "Database per tenant: maximum isolation, maximum complexity. Schema per tenant: best ROI. Row-scoped: cheap, but every query carries tenant_id (trap: no index = slow). Column-scoped: never. Rule: start simple, migrate when you need to. Current project requires schema per tenant + separate read models for scale." },
    },
  ],

  playground: [
    { title: "Bezier playground", kind: "canvas", note: "Drag handles, read the easing curve." },
    { title: "Tokenizer viewer", kind: "widget", note: "Paste text, inspect BPE tokens live." },
    { title: "CI/CD graph", kind: "graph", note: "Animated pipeline runs with risk tags." },
  ],

  oss: [
    {
      repo: "laravel-fintech-core",
      owner: "vitorgabrieldev",
      desc: { pt: "Core bancário com ledger de partidas dobradas, contas multi-tenant e transações auditáveis.", en: "Banking core with double-entry ledger, multi-tenant accounts and auditable transactions." },
      stars: 42,
      lang: "PHP",
      kind: { pt: "Autor", en: "Author" },
    },
    {
      repo: "risklog",
      owner: "vitorgabrieldev",
      desc: { pt: "Camada de CI/CD que resume deploys em linguagem natural — o que quebrou, por quê, quem deve olhar.", en: "CI/CD layer that summarises deploys in natural language — what broke, why, who should look." },
      stars: 18,
      lang: "TypeScript",
      kind: { pt: "Autor", en: "Author" },
    },
    {
      repo: "matetatica-web",
      owner: "vitorgabrieldev",
      desc: { pt: "Plataforma de ensino para matemática adaptativa — motor de exercícios + repetição espaçada.", en: "Teaching platform for adaptive math — exercise engine + spaced repetition." },
      stars: 11,
      lang: "Laravel",
      kind: { pt: "Autor", en: "Author" },
    },
    {
      repo: "laravel/framework",
      owner: "laravel",
      desc: { pt: "Pequenos fixes e PRs de docs upstream — type hints, casos extremos do query builder.", en: "Small fixes and docs PRs upstream — type hints, query builder edge cases." },
      stars: null,
      lang: "PHP",
      kind: { pt: "Contribuidor", en: "Contributor" },
    },
    {
      repo: "spatie/laravel-permission",
      owner: "spatie",
      desc: { pt: "Bugfix para invalidação de cache de permissão com escopo de time em setups multi-guard.", en: "Bugfix for team-scoped permission cache invalidation in multi-guard setups." },
      stars: null,
      lang: "PHP",
      kind: { pt: "Contribuidor", en: "Contributor" },
    },
    {
      repo: "dotfiles",
      owner: "vitorgabrieldev",
      desc: { pt: "Meu config de neovim + tmux + zsh. Nada revolucionário, só honesto.", en: "My neovim + tmux + zsh config. Nothing revolutionary, just honest." },
      stars: 7,
      lang: "Lua",
      kind: { pt: "Autor", en: "Author" },
    },
  ],
};
