/* Shared data — projects, timeline, skills. */
window.PORTFOLIO_DATA = {
  meta: {
    name: "Vitor Gabriel de Oliveira",
    role: "Full Stack Engineer",
    location: "Londrina, BR",
    tz: "UTC−3",
    email: "contact@vitorgabriel.dev",
    whatsapp: "+55 43 98487-3807",
    github: "vitorgabrieldev",
  },

  projects: [
    {
      id: "laravel-fintech",
      name: "Laravel Fintech Core",
      year: "2025",
      category: "Fintech Platform",
      role: "Lead Engineer",
      stack: ["Laravel", "PostgreSQL", "Redis", "Docker"],
      summary: "Banking core with ledger, transactions and multi-tenant accounts. Focus on consistency guarantees and throughput.",
      impact: "Settled the foundation for a complete banking system with double-entry ledger and auditable transactions.",
      url: "https://github.com/vitorgabrieldev/laravel-fintech-core",
      accent: "#c96442",
      featured: true,
    },
    {
      id: "risklog",
      name: "Risklog",
      year: "2025",
      category: "Deployment Intelligence",
      role: "Full Stack",
      stack: ["Laravel", "CI/CD", "GitHub Actions"],
      summary: "CI/CD integration that tracks risk per deploy, summarising changes, owners and probable blast radius.",
      impact: "Team adopted it as a release checklist — fewer surprises after deploys.",
      url: "https://github.com/vitorgabrieldev/risklog-api",
      accent: "#6b7a4a",
      featured: true,
    },
    {
      id: "dubflow",
      name: "DubFlow",
      year: "2024",
      category: "Social Platform",
      role: "Full Stack",
      stack: ["Laravel", "Next.js", "TypeScript"],
      summary: "Community platform for voice-over professionals — casting, portfolio, direct messages.",
      impact: "Shipped end-to-end: API, auth, frontend, deploy pipeline.",
      url: "https://github.com/vitorgabrieldev/dubflow.pro.br",
      accent: "#8a5a8c",
      featured: true,
    },
    {
      id: "general-agent",
      name: "General Agent Terminal",
      year: "2025",
      category: "AI · Linux",
      role: "Experimental",
      stack: ["Python", "Mistral", "Linux"],
      summary: "Mistral-powered terminal agent that reasons about shell actions before executing them.",
      impact: "Personal research prototype — exploring LLM-driven sysadmin workflows.",
      url: "https://github.com/vitorgabrieldev/general-agent-terminal-linux",
      accent: "#3d5a7a",
      featured: false,
    },
    {
      id: "blockchain",
      name: "Blockchain Prototypes",
      year: "2024",
      category: "Blockchain",
      role: "Researcher",
      stack: ["Solidity", "Ethereum", "Node.js"],
      summary: "Experiments with DApps, custom chain logic and consensus — validating decentralised integrations.",
      impact: "Gained depth on EVM, signatures and on-chain vs off-chain trade-offs.",
      url: "https://github.com/vitorgabrieldev/Blockchain",
      accent: "#b58844",
      featured: false,
    },
    {
      id: "motion-recognition",
      name: "Hand Motion Recognition",
      year: "2024",
      category: "Computer Vision",
      role: "Full Stack",
      stack: ["Python", "OpenCV"],
      summary: "Real-time hand gesture interface for interaction optimisation.",
      impact: "Explored CV pipelines and low-latency video processing on commodity hardware.",
      url: "https://github.com/vitorgabrieldev/motion-recognition-for-interaction-optimization",
      accent: "#4a7a6b",
      featured: false,
    },
    {
      id: "rotina",
      name: "Rotina",
      year: "2024",
      category: "Internal Tools",
      role: "Full Stack",
      stack: ["Laravel", "PHP"],
      summary: "Business organisation platform — weekly cadence, ownership, blockers.",
      impact: "Replaced 3 spreadsheets for a small team.",
      url: "https://github.com/vitorgabrieldev/rotina.pro.br",
      accent: "#7a5a4a",
      featured: false,
    },
    {
      id: "painel-startup",
      name: "Risklog Admin Panel",
      year: "2024",
      category: "Admin Dashboard",
      role: "Full Stack",
      stack: ["Laravel", "Blade", "Tailwind"],
      summary: "Operations console for Risklog — deploys, users, policy thresholds.",
      impact: "Gave the ops team direct control without engineering hand-offs.",
      url: "https://github.com/vitorgabrieldev/painel.startup.dev.br",
      accent: "#5a4a7a",
      featured: false,
    },
  ],

  timeline: [
    { year: "2026", company: "Clickweb", role: "Full Stack Pleno · Projetos", where: "Londrina, BR", current: true, notes: "Ownership of technical direction on key deliveries. Architecture, DevOps, mentoring." },
    { year: "2024", company: "Matetática", role: "Full Stack (TI)", where: "Londrina, BR", notes: "Platform for math tutoring — end-to-end from Laravel API to React frontend and deploy." },
    { year: "2024", company: "Clickweb", role: "Full Stack Junior", where: "Londrina, BR", notes: "Promoted from intern. Extended responsibilities across infra, Laravel and front-end." },
    { year: "2023", company: "Clickweb", role: "Full Stack Intern", where: "Londrina, BR", notes: "First professional role. Learned production discipline, support flow, release cadence." },
    { year: "2022", company: "Marista Escola Social Irmão Acácio", role: "Ensino Médio Técnico em Informática para Internet", where: "Londrina, BR", notes: "Technical high-school — foundations in CS, networks, and web development." },
  ],

  skills: {
    "Backend": ["Laravel", "PHP", "Node.js", "Express", "Apollo", "GraphQL", "REST", "MongoDB", "PostgreSQL", "JWT", "PM2"],
    "Frontend": ["React", "Next.js", "TypeScript", "Vue", "Angular", "Tailwind", "SASS/SCSS", "jQuery"],
    "Infra / DevOps": ["Docker", "Kubernetes", "CI/CD", "GitHub Actions", "Nginx", "Linux", "DigitalOcean", "AWS"],
    "Exploratory": ["Solidity", "Ethereum", "LLMs (Mistral/OpenAI)", "Computer Vision"],
  },

  journal: [
    {
      slug: "ledger-consistency",
      title: "Why your ledger needs double-entry, even on day one",
      date: "2026-03-14",
      read: "7 min",
      kicker: "Architecture",
      excerpt: "Consistency guarantees are cheap to add early and ruinous to retrofit. A note from Laravel Fintech Core.",
    },
    {
      slug: "risklog-post",
      title: "Shipping Risklog: turning deploys into paragraphs",
      date: "2026-02-02",
      read: "5 min",
      kicker: "Case study",
      excerpt: "A CI/CD layer that summarises changes in natural language — what broke, why, and who should look.",
    },
    {
      slug: "kv-attention",
      title: "Attention from scratch: notes while reading the GPT paper",
      date: "2025-12-20",
      read: "11 min",
      kicker: "Learning in public",
      excerpt: "Tokenisation, vocabularies, Q/K/V — building intuition by implementing a tiny transformer in pure PHP.",
    },
    {
      slug: "laravel-tenancy",
      title: "Multi-tenancy in Laravel: four shapes, one trap",
      date: "2025-11-11",
      read: "8 min",
      kicker: "Architecture",
      excerpt: "Database-per-tenant, schema-per-tenant, column-scoped, or row-scoped — how to pick without regret.",
    },
  ],

  playground: [
    { title: "Bezier playground", kind: "canvas", note: "Drag handles, read the easing curve." },
    { title: "Tokenizer viewer", kind: "widget", note: "Paste text, inspect BPE tokens live." },
    { title: "CI/CD graph", kind: "graph", note: "Animated pipeline runs with risk tags." },
  ],

  oss: [
    {
      repo: "laravel-fintech-core",
      owner: "vitorgabrieldev",
      desc: "Banking core with double-entry ledger, multi-tenant accounts and auditable transactions.",
      stars: 42,
      lang: "PHP",
      kind: "Author",
    },
    {
      repo: "risklog",
      owner: "vitorgabrieldev",
      desc: "CI/CD layer that summarises deploys in natural language — what broke, why, who should look.",
      stars: 18,
      lang: "TypeScript",
      kind: "Author",
    },
    {
      repo: "matetatica-web",
      owner: "vitorgabrieldev",
      desc: "Teaching platform for adaptive math — exercise engine + spaced repetition.",
      stars: 11,
      lang: "Laravel",
      kind: "Author",
    },
    {
      repo: "laravel/framework",
      owner: "laravel",
      desc: "Small fixes and docs PRs upstream — type hints, query builder edge cases.",
      stars: null,
      lang: "PHP",
      kind: "Contributor",
    },
    {
      repo: "spatie/laravel-permission",
      owner: "spatie",
      desc: "Bugfix for team-scoped permission cache invalidation in multi-guard setups.",
      stars: null,
      lang: "PHP",
      kind: "Contributor",
    },
    {
      repo: "dotfiles",
      owner: "vitorgabrieldev",
      desc: "My neovim + tmux + zsh config. Nothing revolutionary, just honest.",
      stars: 7,
      lang: "Lua",
      kind: "Author",
    },
  ],
};
